/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_hostedclient_free: (a: number, b: number) => void;
export const hostedclient_close: (a: number) => void;
export const hostedclient_close_pane: (a: number) => [number, number];
export const hostedclient_focus_next_pane: (a: number) => [number, number];
export const hostedclient_resize: (a: number, b: number, c: number) => void;
export const hostedclient_send_key: (a: number, b: number, c: number) => [number, number];
export const hostedclient_set_ctrl_latch: (a: number, b: number) => void;
export const hostedclient_split_pane: (a: number, b: number, c: number) => [number, number];
export const start: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const start_hosted: (a: number, b: number, c: number, d: number, e: number, f: number, g: any, h: number) => any;
export const start_webtransport: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___u32__u32__i32__true_: (a: number, b: number, c: number, d: number) => number;
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___js_sys_e1caa9b86f7b459a___Function_fn_wasm_bindgen_c41d5cbf289b5539___JsValue_____wasm_bindgen_c41d5cbf289b5539___sys__Undefined___js_sys_e1caa9b86f7b459a___Function_fn_wasm_bindgen_c41d5cbf289b5539___JsValue_____wasm_bindgen_c41d5cbf289b5539___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___u32__u32______true_: (a: number, b: number, c: number, d: number) => void;
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___wasm_bindgen_c41d5cbf289b5539___JsValue__core_608f92abc48d28da___result__Result_____wasm_bindgen_c41d5cbf289b5539___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___wasm_bindgen_c41d5cbf289b5539___sys__Undefined__core_608f92abc48d28da___result__Result_____wasm_bindgen_c41d5cbf289b5539___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___wasm_bindgen_c41d5cbf289b5539___sys__Undefined__core_608f92abc48d28da___result__Result_____wasm_bindgen_c41d5cbf289b5539___JsError___true__15: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___web_sys_3ca46e9073013fcd___features__gen_MessageEvent__MessageEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke___web_sys_3ca46e9073013fcd___features__gen_MessageEvent__MessageEvent______true__13: (a: number, b: number, c: any) => void;
export const wasm_bindgen_c41d5cbf289b5539___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
