//! Binary-level end-to-end tests for `phux rec` (ADR-0060): the headless
//! recorder, the offline `--from` renderer, and the observer guarantee.
//!
//! Same harness discipline as `run_wait_e2e.rs` and `spatial_e2e.rs`: a real
//! `phux server` child on a private UDS, each verb its own subprocess,
//! guard-killed on drop. Two things are specific to this file:
//!
//!   * **Sockets live at the root of `/tmp`, not under `tempdir()`.** macOS
//!     caps `sun_path` at 104 bytes and this file's `#[ignore]` reason means
//!     it is usually run by hand from a deep worktree; a `TMPDIR` under
//!     `/var/folders/.../T/` plus a name is already half that budget. The
//!     path is `pid`- and counter-qualified, and unlinked on guard drop.
//!   * **The render tests read `docs/assets/recording-demo.cast`**, the
//!     committed demo asset, instead of synthesising a fixture. That asset
//!     is regenerated by `scripts/demo-record.sh` and shipped in
//!     `docs/consumers/recording.md`, so pointing the decoder at it makes a
//!     corrupted or unreadable commit of it a test failure rather than a
//!     broken image in the docs.
//!
//! The load-bearing test here is `rec_does_not_resize_the_recorded_pane`.
//! `phux-client`'s unit test proves the recorder never *sends* `ATTACH`;
//! this one proves the consequence against a real server with a real human
//! attached, which is the only place the regression would actually hurt.

#![allow(clippy::expect_used, reason = "tests")]
#![allow(clippy::unwrap_used, reason = "tests")]
#![allow(clippy::panic, reason = "tests")]

use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicU32, Ordering};
use std::time::{Duration, Instant};

use phux_record::cast::{EventCode, read_cast};
use portable_pty::{CommandBuilder, PtySize, native_pty_system};

/// Path to the freshly-built `phux` binary, injected by cargo.
const PHUX: &str = env!("CARGO_BIN_EXE_phux");

/// The pre-seeded session name every test drives against.
const SESSION: &str = "work";

/// How long to wait for the server to bind its socket (cold-start bound).
const SOCKET_DEADLINE: Duration = Duration::from_secs(30);

/// Poll cadence for every wait loop in this file.
const POLL: Duration = Duration::from_millis(50);

/// Monotonic counter so concurrent tests never collide on a socket path.
static COUNTER: AtomicU32 = AtomicU32::new(0);

/// The committed demo asset, which doubles as this file's render fixture.
fn demo_cast() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/assets/recording-demo.cast")
}

/// A running `phux server`, killed and unlinked when the guard drops.
struct ServerGuard {
    child: Child,
    socket: PathBuf,
    // Output files live here; only the socket needs the short path.
    dir: tempfile::TempDir,
}

impl Drop for ServerGuard {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
        // The server unlinks on clean shutdown; we SIGKILL it, so a stale
        // socket in /tmp would otherwise outlive every run.
        let _ = std::fs::remove_file(&self.socket);
    }
}

impl ServerGuard {
    fn start() -> Self {
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let socket = PathBuf::from(format!("/tmp/phux-rec-e2e-{}-{n}.sock", std::process::id()));
        let _ = std::fs::remove_file(&socket);
        let child = Command::new(PHUX)
            .args(["server", "--session", SESSION, "--socket"])
            .arg(&socket)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .expect("spawn phux server");
        let guard = Self {
            child,
            socket,
            dir: tempfile::tempdir().expect("create temp dir for outputs"),
        };
        let deadline = Instant::now() + SOCKET_DEADLINE;
        while Instant::now() < deadline {
            if guard.socket.exists() {
                return guard;
            }
            std::thread::sleep(POLL);
        }
        panic!(
            "phux server did not bind {} within {SOCKET_DEADLINE:?}",
            guard.socket.display()
        );
    }

    /// An output path inside this guard's scratch directory.
    fn out(&self, name: &str) -> PathBuf {
        self.dir.path().join(name)
    }

    /// Build `phux <verb> --socket <sock> <rest...>`. `--socket` goes right
    /// after the verb: `send-keys` uses `trailing_var_arg`, so a trailing
    /// `--socket` would be swallowed into the keys and the verb would fall
    /// back to the user's real default socket.
    fn cmd(&self, args: &[&str]) -> Command {
        let (verb, rest) = args.split_first().expect("at least a verb");
        let mut c = Command::new(PHUX);
        c.arg(verb)
            .arg("--socket")
            .arg(&self.socket)
            .args(rest)
            .stdin(Stdio::null());
        c
    }

    fn success(&self, args: &[&str]) -> String {
        let out = self.cmd(args).output().expect("run phux verb");
        assert!(
            out.status.success(),
            "phux {args:?} exited {:?}; stderr={}",
            out.status.code(),
            String::from_utf8_lossy(&out.stderr)
        );
        String::from_utf8_lossy(&out.stdout).into_owned()
    }

    fn json(&self, args: &[&str]) -> serde_json::Value {
        let stdout = self.success(args);
        serde_json::from_str(&stdout)
            .unwrap_or_else(|err| panic!("invalid JSON from phux {args:?}: {err}: {stdout}"))
    }

    /// The recorded pane's current grid, read through the side-effect-free
    /// `snapshot` path (which, unlike `--rendered`, never attaches).
    fn pane_size(&self) -> (u64, u64) {
        let snapshot = self.json(&["snapshot", "--json", SESSION]);
        (
            snapshot["cols"].as_u64().expect("snapshot cols"),
            snapshot["rows"].as_u64().expect("snapshot rows"),
        )
    }
}

/// Run `phux rec --from <fixture> -o <out>` with extra flags, returning the
/// parsed `--json` result object. No server is involved: `--from` re-renders
/// an existing cast entirely offline.
fn render(out: &Path, extra: &[&str]) -> serde_json::Value {
    let output = Command::new(PHUX)
        .arg("rec")
        .arg("--from")
        .arg(demo_cast())
        .arg("-o")
        .arg(out)
        .arg("--json")
        .args(extra)
        .stdin(Stdio::null())
        .output()
        .expect("run phux rec --from");
    assert!(
        output.status.success(),
        "phux rec --from exited {:?}; stderr={}",
        output.status.code(),
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    serde_json::from_str(&stdout)
        .unwrap_or_else(|err| panic!("invalid JSON from `phux rec --from`: {err}: {stdout}"))
}

fn read_bytes(path: &Path) -> Vec<u8> {
    let mut bytes = Vec::new();
    std::fs::File::open(path)
        .unwrap_or_else(|err| panic!("open {}: {err}", path.display()))
        .read_to_end(&mut bytes)
        .expect("read output");
    bytes
}

/// A real `phux attach` TUI on a real PTY, killed on drop.
///
/// Its only job in this file is to put the pane at a size that is NOT the
/// no-TTY default, so an errant session-scoped `ATTACH` from the recorder
/// would be *observable*. See `rec_does_not_resize_the_recorded_pane`.
struct AttachedClient {
    child: Box<dyn portable_pty::Child + Send + Sync>,
    _config: tempfile::TempDir,
}

impl Drop for AttachedClient {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

impl AttachedClient {
    /// Attach at `cols`x`rows` and block until the server has reshaped the
    /// pane away from the 80x24 no-TTY default.
    fn start(server: &ServerGuard, cols: u16, rows: u16) -> Self {
        let pair = native_pty_system()
            .openpty(PtySize {
                rows,
                cols,
                pixel_width: 0,
                pixel_height: 0,
            })
            .expect("open attach PTY");
        let config = tempfile::tempdir().expect("isolated config dir");
        let mut command = CommandBuilder::new(PHUX);
        command.args([
            "attach",
            "--socket",
            server.socket.to_str().expect("UTF-8 socket"),
            SESSION,
        ]);
        command.env("SHELL", "/bin/sh");
        command.env("TERM", "xterm-256color");
        command.env("RUST_LOG", "off");
        command.env("XDG_CONFIG_HOME", config.path());
        let child = pair
            .slave
            .spawn_command(command)
            .expect("spawn attached TUI");
        drop(pair.slave);

        // Drain paint output continuously: an undrained PTY backpressures
        // the real client, which then stops servicing the resize it just
        // negotiated and the wait below times out for the wrong reason.
        let mut reader = pair.master.try_clone_reader().expect("clone PTY reader");
        std::thread::spawn(move || {
            let mut bytes = [0u8; 8192];
            while let Ok(read) = reader.read(&mut bytes) {
                if read == 0 {
                    break;
                }
            }
        });

        let attached = Self {
            child,
            _config: config,
        };
        let deadline = Instant::now() + Duration::from_secs(15);
        while Instant::now() < deadline {
            if server.pane_size() != (80, 24) {
                return attached;
            }
            std::thread::sleep(POLL);
        }
        panic!("attached client never resized the pane away from 80x24");
    }
}

#[test]
#[ignore = "spawns a real phux server; starves in the full parallel pool. Run via `just e2e`."]
fn rec_records_a_live_pane_to_a_playable_cast() {
    let server = ServerGuard::start();
    let out = server.out("live.cast");
    let (cols, rows) = server.pane_size();

    // Drive the pane from a second process WHILE the recorder observes, so
    // the marker arrives as a streamed `TERMINAL_OUTPUT` delta rather than
    // riding in on the priming snapshot. That is the path a recording
    // actually exercises.
    let socket = server.socket.clone();
    let driver = std::thread::spawn(move || {
        std::thread::sleep(Duration::from_millis(500));
        Command::new(PHUX)
            .args(["send-keys", "--socket"])
            .arg(&socket)
            .args([SESSION, "echo REC_E2E_LIVE_MARKER", "Enter"])
            .stdin(Stdio::null())
            .status()
            .expect("send-keys during recording");
    });

    server.success(&[
        "rec",
        SESSION,
        "-o",
        out.to_str().expect("UTF-8 out"),
        "--duration",
        "3",
    ]);
    driver.join().expect("driver thread");

    let file = std::fs::File::open(&out).expect("open recorded cast");
    let (header, events) =
        read_cast(std::io::BufReader::new(file)).expect("the recorded cast must parse");
    assert_eq!(
        (u64::from(header.cols), u64::from(header.rows)),
        (cols, rows),
        "the cast header must carry the pane's real grid, not a guess"
    );
    assert!(
        events
            .iter()
            .any(|event| event.code == EventCode::Output
                && event.data.contains("REC_E2E_LIVE_MARKER")),
        "the text typed during the take must appear in an output event; got {} events",
        events.len()
    );
    assert!(
        events.iter().all(|event| event.code != EventCode::Input),
        "recordings must never carry input events (passwords do not go in casts)"
    );
}

/// The observer guarantee, proved against a real server with a real human
/// attached. This is the reason `phux rec` speaks `ATTACH_TERMINAL` and not
/// `ATTACH`; see `phux-client`'s `record` module docs.
#[test]
#[ignore = "spawns a real phux server; starves in the full parallel pool. Run via `just e2e`."]
fn rec_does_not_resize_the_recorded_pane() {
    let server = ServerGuard::start();
    // A human is attached at 100x30. This is not decoration: a headless
    // caller's `current_viewport()` reports 80x24, so against an 80x24 pane
    // an errant ATTACH would resize it to the size it already was and this
    // test would pass while the bug shipped. The assertion below only has
    // teeth because the pane is somewhere else.
    let _human = AttachedClient::start(&server, 100, 30);
    let before = server.pane_size();
    assert_ne!(
        before,
        (80, 24),
        "the attached client must move the pane off the no-TTY default or \
         this test cannot observe the regression it exists to catch"
    );

    let out = server.out("observer.cast");
    server.success(&[
        "rec",
        SESSION,
        "-o",
        out.to_str().expect("UTF-8 out"),
        "--duration",
        "2",
    ]);

    let after = server.pane_size();
    assert_eq!(
        after, before,
        "`phux rec` RESIZED the pane it was recording, from {before:?} to \
         {after:?}. The recorder must speak ATTACH_TERMINAL (L1 §5.1), a \
         non-resizing observer subscription. A session-scoped ATTACH \
         instead runs the server's `apply_attach_viewport`, which drives \
         TIOCSWINSZ on every pane in the session under the default \
         `WindowSize::Smallest` policy — and a headless recorder has no \
         TTY, so the viewport it contributes to that minimum is the 80x24 \
         fallback. The consequence is that running `phux rec` against a \
         session a human is working in SHRINKS THEIR PANES OUT FROM UNDER \
         THEM, reflowing and truncating live output. Look for a \
         FrameKind::Attach or FrameKind::ViewportResize that has crept into \
         phux-client's `record` module."
    );
}

#[test]
#[ignore = "renders the committed demo asset; grouped with the rest of the rec lane."]
fn rec_from_cast_renders_a_gif() {
    let dir = tempfile::tempdir().expect("temp dir");
    let out = dir.path().join("demo.gif");
    let result = render(&out, &["--fps", "10"]);

    assert_eq!(result["format"], "gif");
    assert_eq!(
        result["truncated"], false,
        "the demo asset must render whole under the default byte cap: {result}"
    );
    assert!(
        result["frames"].as_u64().expect("frames") > 0,
        "a GIF with no frames is not an animation: {result}"
    );

    let bytes = read_bytes(&out);
    assert_eq!(
        &bytes[..6],
        b"GIF89a",
        "GIF89a is the only header that carries the graphic-control \
         extensions per-frame delays live in"
    );
    assert!(
        bytes.len() > 1024,
        "a {}-byte GIF is a header and not a recording",
        bytes.len()
    );
    assert_eq!(
        bytes.last(),
        Some(&0x3b),
        "the GIF trailer byte must be present, or a strict decoder \
         (Preview, Safari) treats the file as truncated"
    );
}

#[test]
#[ignore = "renders the committed demo asset; grouped with the rest of the rec lane."]
fn rec_from_cast_renders_an_apng() {
    let dir = tempfile::tempdir().expect("temp dir");
    let out = dir.path().join("demo.apng");
    let result = render(&out, &["--fps", "10"]);

    assert_eq!(result["format"], "apng");
    assert!(result["frames"].as_u64().expect("frames") > 0);

    let bytes = read_bytes(&out);
    assert_eq!(
        &bytes[..8],
        b"\x89PNG\r\n\x1a\n",
        "APNG is a PNG: the eight-byte signature is mandatory"
    );
    assert!(
        bytes.windows(4).any(|chunk| chunk == b"acTL"),
        "no acTL chunk: without the animation control chunk every decoder \
         renders this as a single still image"
    );
}

#[test]
#[ignore = "renders the committed demo asset; grouped with the rest of the rec lane."]
fn rec_json_emits_exactly_one_object_on_stdout() {
    let dir = tempfile::tempdir().expect("temp dir");
    let out = dir.path().join("one.gif");
    let output = Command::new(PHUX)
        .arg("rec")
        .arg("--from")
        .arg(demo_cast())
        .arg("-o")
        .arg(&out)
        .arg("--json")
        .stdin(Stdio::null())
        .output()
        .expect("run phux rec --from --json");
    assert!(output.status.success());

    // A consumer pipes this straight into `jq`, so a progress spinner or a
    // second line would break the contract even though both would still be
    // "valid JSON somewhere in there".
    let stdout = String::from_utf8(output.stdout).expect("UTF-8 stdout");
    let values: Vec<serde_json::Value> = serde_json::Deserializer::from_str(&stdout)
        .into_iter::<serde_json::Value>()
        .collect::<Result<_, _>>()
        .unwrap_or_else(|err| panic!("stdout is not a JSON stream: {err}: {stdout:?}"));
    assert_eq!(
        values.len(),
        1,
        "stdout must be exactly one object; got {}: {stdout:?}",
        values.len()
    );
    assert!(
        values[0].is_object(),
        "the result must be an object, not a bare scalar: {stdout:?}"
    );
    assert_eq!(
        stdout.trim_end_matches('\n').lines().count(),
        1,
        "the object must be one line, so `read -r` and `jq -c` both work: {stdout:?}"
    );
    for key in [
        "path",
        "format",
        "bytes",
        "frames",
        "cols",
        "rows",
        "truncated",
    ] {
        assert!(
            values[0].get(key).is_some(),
            "the result contract is missing `{key}`: {stdout:?}"
        );
    }
}

#[test]
#[ignore = "spawns a real phux server; starves in the full parallel pool. Run via `just e2e`."]
fn rec_duration_flag_bounds_the_capture() {
    let server = ServerGuard::start();
    let out = server.out("bounded.cast");
    let started = Instant::now();
    server.success(&[
        "rec",
        SESSION,
        "-o",
        out.to_str().expect("UTF-8 out"),
        "--duration",
        "2",
    ]);
    let elapsed = started.elapsed();

    // `--duration` is the ONLY stop condition for a live pane that never
    // exits, so an off-by-one here is the difference between a demo script
    // and a process that runs until the disk fills.
    assert!(
        elapsed >= Duration::from_millis(1_900),
        "`--duration 2` returned after {elapsed:?}; it must actually record \
         for the requested window, not return early"
    );
    assert!(
        elapsed < Duration::from_secs(8),
        "`--duration 2` took {elapsed:?}; the deadline is not being honoured"
    );
    assert!(
        out.exists(),
        "a bounded capture must still write its output"
    );
}

#[test]
#[ignore = "grouped with the rest of the rec lane."]
fn rec_unknown_extension_fails_with_a_nonzero_exit_and_an_actionable_message() {
    let dir = tempfile::tempdir().expect("temp dir");
    let out = dir.path().join("demo.mov");
    let output = Command::new(PHUX)
        .arg("rec")
        .arg("--from")
        .arg(demo_cast())
        .arg("-o")
        .arg(&out)
        .stdin(Stdio::null())
        .output()
        .expect("run phux rec --from with a bad extension");

    assert_eq!(
        output.status.code(),
        Some(1),
        "an unrenderable extension must fail, not silently pick a format"
    );
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    assert!(
        stderr.contains("mov") && stderr.contains("--format"),
        "the diagnostic must name the rejected extension and the escape \
         hatch; got: {stderr}"
    );
    assert!(
        !out.exists(),
        "a rejected format must not leave a partial file behind"
    );
}

#[test]
#[ignore = "renders the committed demo asset; grouped with the rest of the rec lane."]
fn rec_max_bytes_reports_truncated_rather_than_filling_the_disk() {
    let dir = tempfile::tempdir().expect("temp dir");
    let whole = dir.path().join("whole.gif");
    let capped = dir.path().join("capped.gif");
    let full = render(&whole, &["--fps", "10"]);
    let short = render(&capped, &["--fps", "10", "--max-bytes", "2048"]);

    assert_eq!(
        short["truncated"], true,
        "hitting the cap must be reported, not swallowed: {short}"
    );
    assert!(
        short["frames"].as_u64().expect("frames") < full["frames"].as_u64().expect("frames"),
        "a capped render must drop frames relative to the whole one: \
         {short} vs {full}"
    );

    // The cap is a stop condition, not a hard ceiling: the encoder finishes
    // the frame it is on and writes the trailer, so the file lands slightly
    // over. What matters is that it stops there instead of running to the
    // full size.
    let bytes = read_bytes(&capped);
    assert!(
        bytes.len() < read_bytes(&whole).len(),
        "the capped file ({} bytes) must be smaller than the whole one",
        bytes.len()
    );
    assert_eq!(
        &bytes[..6],
        b"GIF89a",
        "a truncated GIF must still be a GIF"
    );
    assert_eq!(
        bytes.last(),
        Some(&0x3b),
        "the encoder must finalize on the way out; a capped file with no \
         trailer is a corrupt file, which is worse than a short one"
    );
}
