// app.zon is the shipping command/shortcut authority. This deliberately reads
// its flat menu declarations rather than the retained native scene fixtures.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export function shippingCommands(source) {
  const rows = [];
  for (const match of source.matchAll(/\.\{ \.label = "([^"]+)", \.command = "([^"]+)"([^\n]*)/g)) {
    const [, label, name, tail] = match;
    const key = tail.match(/\.key = "([^"]+)"/)?.[1] ?? '';
    const modifiers = tail.match(/\.modifiers = \.\{([^}]+)\}/)?.[1] ?? '';
    const chord = ['primary', 'control', 'option', 'shift'].filter(mod => modifiers.includes(`"${mod}"`));
    rows.push({ index: rows.length, name, label: label.replace(/…$/, ''), shortcut: formatShortcut(key, chord) });
  }
  return rows;
}

function formatShortcut(key, modifiers) {
  if (!key) return '';
  const names = { primary: 'Cmd', control: 'Ctrl', option: 'Option', shift: 'Shift' };
  const keys = { arrowleft: 'Left', arrowright: 'Right', arrowup: 'Up', arrowdown: 'Down' };
  return [...modifiers.map(mod => names[mod]), keys[key] ?? key.toUpperCase()].join('+');
}

export function generatedCatalog(source) {
  const rows = shippingCommands(source).map(row => `  { index: ${row.index}, name: ${JSON.stringify(row.name)}, label: utf8Bytes(${JSON.stringify(row.label)}), shortcut: asciiBytes(${JSON.stringify(row.shortcut)}) },`);
  return `// Generated by scripts/command-catalog.mjs from app.zon.\nimport { asciiBytes, utf8Bytes } from "@native-sdk/core";\n\nexport interface CommandDefinition {\n  readonly index: number;\n  readonly name: string;\n  readonly label: Uint8Array;\n  readonly shortcut: Uint8Array;\n}\n\nexport const COMMAND_CATALOG: readonly CommandDefinition[] = [\n${rows.join('\n')}\n];\n`;
}

const source = new URL('../app.zon', import.meta.url);
const output = new URL('../src/command-catalog.ts', import.meta.url);
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const generated = generatedCatalog(readFileSync(source, 'utf8'));
  if (process.argv.includes('--check')) {
    if (readFileSync(output, 'utf8') !== generated) throw new Error('Command catalog differs from app.zon; run node scripts/command-catalog.mjs');
  } else writeFileSync(output, generated);
}
