// app.zon is the shipping command/shortcut authority. This deliberately reads
// its flat menu declarations rather than the retained native scene fixtures.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export function shippingCommands(source) {
  const rows = [];
  for (const match of source.matchAll(/\.\{ \.label = "([^"]+)", \.command = "([^"]+)"([^\n]*)/g)) {
    const [, label, name, tail] = match;
    const key = tail.match(/\.key = "([^"]+)"/)?.[1] ?? '';
    const modifiers = tail.match(/\.modifiers = \.\{([^}]+)\}/)?.[1] ?? '';
    const chord = ['primary', 'control', 'option', 'shift'].filter(mod => modifiers.includes(`"${mod}"`));
    rows.push({ index: rows.length, name, label: label.replace(/…$/, ''), shortcut: formatShortcut(key, chord) });
  }
  return rows;
}

function formatShortcut(key, modifiers) {
  if (!key) return '';
  const names = { primary: 'Cmd', control: 'Ctrl', option: 'Option', shift: 'Shift' };
  const keys = { arrowleft: 'Left', arrowright: 'Right', arrowup: 'Up', arrowdown: 'Down' };
  return [...modifiers.map(mod => names[mod]), keys[key] ?? key.toUpperCase()].join('+');
}

export function generatedCatalog(source) {
  const rows = shippingCommands(source).map(row => `  { index: ${row.index}, name: ${JSON.stringify(row.name)}, label: utf8Bytes(${JSON.stringify(row.label)}), shortcut: asciiBytes(${JSON.stringify(row.shortcut)}) },`);
  return `// Generated by scripts/command-catalog.mjs from app.zon.\nimport { asciiBytes, utf8Bytes } from "@native-sdk/core";\n\nexport interface CommandDefinition {\n  readonly index: number;\n  readonly name: string;\n  readonly label: Uint8Array;\n  readonly shortcut: Uint8Array;\n}\n\nexport const COMMAND_CATALOG: readonly CommandDefinition[] = [\n${rows.join('\n')}\n];\n`;
}

function zigModifiers(tail) {
  const body = tail.match(/\.modifiers = \.\{([^}]+)\}/)?.[1] ?? '';
  const values = [...body.matchAll(/"(primary|command|control|option|shift)"/g)].map(match => `.${match[1]} = true`);
  return values.length === 0 ? '.{}' : `.{ ${values.join(', ')} }`;
}

function zigMenuItems(source) {
  return [...source.matchAll(/\.\{ (\.label = "([^"\n]+)", \.command = "([^"\n]+)"([^\n]*)|\.separator = true[^\n]*)/g)].map(match => {
    if (!match[2]) return '        .{ .separator = true },';
    const key = match[4].match(/\.key = "([^"\n]+)"/)?.[1] ?? '';
    return `        .{ .label = ${JSON.stringify(match[2])}, .command = ${JSON.stringify(match[3])}, .key = ${JSON.stringify(key)}, .modifiers = ${zigModifiers(match[4])} },`;
  }).join('\n');
}

export function generatedShippingFixture(source) {
  const menus = [...source.matchAll(/\.\{ \.title = "([^"\n]+)", \.items = \.\{([\s\S]*?)\n\s*\} \},/g)];
  if (menus.length === 0) throw new Error('No shipping menus parsed from app.zon');
  const menuRows = menus.map(match => `    .{ .title = ${JSON.stringify(match[1])}, .items = &.{\n${zigMenuItems(match[2])}\n    } },`).join('\n');
  const shortcuts = [...source.matchAll(/\.\{ \.id = "([^"\n]+)", \.key = "([^"\n]+)"([^\n]*)/g)];
  if (shortcuts.length === 0) throw new Error('No shipping shortcuts parsed from app.zon');
  const shortcutRows = shortcuts.map(match => `    .{ .id = ${JSON.stringify(match[1])}, .key = ${JSON.stringify(match[2])}, .modifiers = ${zigModifiers(match[3])} },`).join('\n');
  return `// Generated by scripts/command-catalog.mjs from app.zon. Test metadata only.\nconst native_sdk = @import("native_sdk");\n\npub const menus: []const native_sdk.Menu = &.{\n${menuRows}\n};\n\npub const shortcuts: []const native_sdk.Shortcut = &.{\n${shortcutRows}\n};\n`;
}

const source = new URL('../app.zon', import.meta.url);
const output = new URL('../src/command-catalog.ts', import.meta.url);
const fixture = new URL('../src/tests/shipping_commands.zig', import.meta.url);
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const generated = generatedCatalog(readFileSync(source, 'utf8'));
  const generatedFixture = generatedShippingFixture(readFileSync(source, 'utf8'));
  if (process.argv.includes('--check')) {
    if (readFileSync(output, 'utf8') !== generated) throw new Error('Command catalog differs from app.zon; run node scripts/command-catalog.mjs');
    if (readFileSync(fixture, 'utf8') !== generatedFixture) throw new Error('Shipping test fixture differs from app.zon; run node scripts/command-catalog.mjs');
  } else {
    writeFileSync(output, generated);
    writeFileSync(fixture, generatedFixture);
  }
}
