//! Client presentation commands over the provider's Ghostty document API.
//! Search results stay owned by the host and are reacquired for navigation:
//! another pane's search or a replica replacement cannot leave borrowed handles
//! in UI state. No terminal input is generated by a presentation command.
const std = @import("std");
const native_sdk = @import("native_sdk");
const contract = @import("provider_contract");
const model_module = @import("../model.zig");
const support = @import("../phux_support.zig");
const interaction = @import("../terminal_interaction.zig");
const selection = @import("../update.zig").remote_selection;
const keyIs = @import("../terminal_runtime.zig").keyIs;
const Command = @import("ts_protocol.zig").NativeCommand;
const Model = model_module.Model;
const State = model_module.RemoteUiState;
const Step = enum { newest, older, newer, current };

pub const Search = struct {
    open: bool = false,
    needle_buf: [@import("../../terminal/session.zig").max_search_needle_bytes]u8 = undefined,
    needle_len: usize = 0,
    count: usize = 0,
    index: usize = 0,
    failed: bool = false,
    paste_pending: bool = false,
    restore_bottom: bool = true,
    restore_row: u64 = 0,
    refresh_pending: bool = false,

    pub fn needle(self: *const Search) []const u8 {
        return self.needle_buf[0..self.needle_len];
    }

    pub fn replacement(self: *const Search) Search {
        return .{
            .open = self.open,
            .needle_buf = self.needle_buf,
            .needle_len = self.needle_len,
            .refresh_pending = self.open,
        };
    }
};

/// A replacement query runs only against a published live owner. The host's
/// generation publication follows BOOTSTRAP_READY, including resize bootstraps
/// that do not repeat the connection's ATTACH_READY barrier.
pub fn resumeReady(model: *Model) void {
    for (&model.remote_ui) |*state| {
        if (state.terminal_ref == null) continue;
        if (!state.search.refresh_pending) continue;
        if (!model.ownerIsCurrent(state.owner)) continue;
        state.search.refresh_pending = false;
        _ = refresh(model, state, .newest);
    }
}

pub fn command(model: *Model, ref: contract.TerminalRef, value: Command) bool {
    if (comptime !support.phux_enabled) return false;
    const state = model.remoteUi(ref) orelse return false;
    if (!model.ownerIsCurrent(state.owner)) return false;
    switch (value) {
        .find => return open(model, state),
        .select_all => return selectAll(model, state),
        .find_next, .find_previous => return refresh(model, state, if (value == .find_next) .older else .newer),
        .clear => return clear(model, state),
        else => return false,
    }
}

fn clear(model: *Model, state: *State) bool {
    const remote = model.phuxForOwner(state.owner) orelse return false;
    remote.clearPresentation(state.owner) catch return false;
    state.selecting = false;
    state.start_anchor = 0;
    state.end_anchor = 0;
    // Keep an open field and its needle, like local Clear, but retire every
    // result and pending field paste that belonged to the erased document.
    state.search.count = 0;
    state.search.index = 0;
    state.search.failed = false;
    state.search.paste_pending = false;
    state.search.restore_bottom = true;
    state.search.restore_row = 0;
    return true;
}

fn open(model: *Model, state: *State) bool {
    if (state.search.open) return true;
    const view = interaction.presentationForOwner(model, state.owner) orelse return false;
    state.search.restore_bottom = view.history_viewport_offset + view.history_visible_rows >= view.history_total_rows;
    state.search.restore_row = view.history_viewport_offset;
    selection.clear(model, state);
    state.search.open = true;
    return true;
}

fn selectAll(model: *Model, state: *State) bool {
    const view = interaction.presentationForOwner(model, state.owner) orelse return false;
    const total = view.history_total_rows;
    const cols = view.cols;
    if (total == 0 or cols == 0 or total > std.math.maxInt(u32)) return false;
    const remote = model.phuxForOwner(state.owner) orelse return false;
    const start = remote.createAnchor(state.owner, .{ .space = .history, .row = 0, .column = 0 }) catch return false;
    const end = remote.createAnchor(state.owner, .{ .space = .history, .row = @intCast(total - 1), .column = cols - 1 }) catch {
        remote.releaseAnchor(state.owner, start);
        return false;
    };
    selection.clear(model, state);
    remote.setSelection(state.owner, start, end, false) catch {
        remote.releaseAnchor(state.owner, start);
        remote.releaseAnchor(state.owner, end);
        return false;
    };
    state.start_anchor = start.opaque_id;
    state.end_anchor = end.opaque_id;
    state.selecting = false;
    return true;
}

pub fn close(model: *Model, state: *State) void {
    if (comptime !support.phux_enabled) return;
    const remote = model.phuxForOwner(state.owner) orelse return;
    remote.clearSearchResults(state.owner);
    selection.clear(model, state);
    if (state.search.restore_bottom) {
        remote.scrollViewport(state.owner, .{ .kind = .bottom }) catch {};
    } else {
        remote.scrollViewport(state.owner, .{ .kind = .top }) catch {};
        remote.scrollViewport(state.owner, .{ .kind = .delta, .value = @intCast(state.search.restore_row) }) catch {};
    }
    state.search = .{};
}

/// A navigation command reruns the provider query before using its anchors.
/// Copy the chosen result before pin/setSelection invalidate borrowed arrays.
fn refresh(model: *Model, state: *State, step: Step) bool {
    if (comptime !support.phux_enabled) return false;
    if (!state.search.open) return false;
    const remote = model.phuxForOwner(state.owner) orelse return false;
    state.search.failed = false;
    selection.clear(model, state);
    if (state.search.needle_len == 0) {
        remote.clearSearchResults(state.owner);
        state.search.count = 0;
        return true;
    }
    const results = remote.search(state.owner, state.search.needle()) catch {
        return failSearch(remote, state);
    };
    state.search.count = results.len;
    if (results.len == 0) return true;
    state.search.index = nextIndex(state.search.index, results.len, step);
    const result = results[state.search.index];
    return reveal(remote, state, result);
}

fn reveal(remote: *support.PhuxProvider, state: *State, result: anytype) bool {
    remote.pinViewport(state.owner, result.start) catch return failSearch(remote, state);
    remote.setSelection(state.owner, result.start, result.end, false) catch return failSearch(remote, state);
    return true;
}

fn failSearch(remote: *support.PhuxProvider, state: *State) bool {
    state.search.failed = true;
    state.search.count = 0;
    remote.clearSelection(state.owner) catch {};
    return false;
}

fn nextIndex(previous: usize, count: usize, step: Step) usize {
    const current = @min(previous, count - 1);
    // Find Next follows the local search: older matches, wrapping at the top.
    return switch (step) {
        .newest => count - 1,
        .older => (current + count - 1) % count,
        .newer => (current + 1) % count,
        .current => current,
    };
}

pub fn prepareCopy(model: *Model, state: *State) bool {
    if (!state.search.open) return true;
    return refresh(model, state, .current);
}

pub fn input(model: *Model, ref: contract.TerminalRef, text: []const u8) bool {
    const state = model.remoteUi(ref) orelse return false;
    return inputState(model, state, text);
}

fn inputState(model: *Model, state: *State, text: []const u8) bool {
    if (!state.search.open or text.len == 0) return false;
    if (!std.unicode.utf8ValidateSlice(text)) return false;
    for (text) |byte| if (byte < 0x20 or byte == 0x7f) return false;
    if (text.len > state.search.needle_buf.len - state.search.needle_len) return false;
    @memcpy(state.search.needle_buf[state.search.needle_len..][0..text.len], text);
    state.search.needle_len += text.len;
    return refresh(model, state, .newest);
}

pub fn paste(model: *Model, ref: contract.TerminalRef, text: []const u8) bool {
    const state = model.remoteUi(ref) orelse return false;
    return pasteState(model, state, text);
}

pub fn pasteForOwner(model: *Model, owner: contract.ReplicaOwner, text: []const u8) bool {
    if (!model.ownerIsCurrent(owner)) return false;
    const state = interaction.stateForOwner(model, owner) orelse return false;
    return pasteState(model, state, text);
}

fn pasteState(model: *Model, state: *State, text: []const u8) bool {
    if (!state.search.open) return false;
    var filtered: [@import("../../terminal/session.zig").max_search_needle_bytes]u8 = undefined;
    const len = pasteLine(text, filtered[0 .. filtered.len - state.search.needle_len]);
    return inputState(model, state, filtered[0..len]);
}

fn pasteLine(text: []const u8, filtered: []u8) usize {
    var len: usize = 0;
    for (text) |byte| {
        if (byte == '\n' or byte == '\r') break;
        if (byte < 0x20 or byte == 0x7f) continue;
        if (len == filtered.len) break;
        filtered[len] = byte;
        len += 1;
    }
    // A bounded paste must never leave half of a UTF-8 scalar in the field.
    while (len > 0 and !std.unicode.utf8ValidateSlice(filtered[0..len])) len -= 1;
    return len;
}

pub fn key(model: *Model, fx: anytype, ref: contract.TerminalRef, event: native_sdk.canvas.WidgetKeyboardEvent) void {
    const state = model.remoteUi(ref) orelse return;
    if (event.modifiers.super and !event.modifiers.control) {
        if (keyIs(event.key, "v")) return interaction.requestPaste(model, fx, ref);
        if (keyIs(event.key, "c")) return interaction.copy(model, fx, ref);
        if (keyIs(event.key, "g")) {
            _ = refresh(model, state, if (event.modifiers.shift) .newer else .older);
            return;
        }
    }
    editKey(model, state, event);
}

fn editKey(model: *Model, state: *State, event: native_sdk.canvas.WidgetKeyboardEvent) void {
    if (keyIs(event.key, "escape")) return close(model, state);
    if (keyIs(event.key, "enter") or keyIs(event.key, "return")) {
        _ = refresh(model, state, if (event.modifiers.shift) .newer else .older);
        return;
    }
    if (!keyIs(event.key, "backspace") and !keyIs(event.key, "delete")) return;
    if (state.search.needle_len == 0) return;
    var end = state.search.needle_len - 1;
    while (end > 0 and state.search.needle_buf[end] & 0xc0 == 0x80) end -= 1;
    state.search.needle_len = end;
    _ = refresh(model, state, .newest);
}

pub const test_support = SourceFixture;

const SourceFixture = struct {
    engine: *@import("ts_engine.zig").Engine,
    a: *support.PhuxProvider,
    b: *support.PhuxProvider,
    owner_a: contract.ReplicaOwner,
    owner_b: contract.ReplicaOwner,

    pub fn init() !SourceFixture {
        if (comptime !support.phux_enabled) return error.SkipZigTest;
        const engine = try @import("ts_engine.zig").Engine.create(std.testing.allocator, std.testing.io);
        errdefer engine.destroy();
        const endpoint: support.PhuxEndpoint = .{ .unix = "/source-consumer-fixture-unused" };
        const a = try support.PhuxProvider.create(std.testing.allocator, std.testing.io, endpoint, null, "a");
        engine.model.phux_provider = a;
        try engine.model.ensurePeerSlots(1);
        const b = try support.PhuxProvider.create(std.testing.allocator, std.testing.io, endpoint, null, "b");
        engine.model.peers.items[0].provider = b;
        try support.PhuxProvider.test_support.attachHost(a.host);
        try support.PhuxProvider.test_support.attachHost(b.host);
        var refs: [contract.workspace.max_replicas]contract.TerminalRef = undefined;
        try std.testing.expect(a.terminalRefs(&refs) > 0);
        const owner_a = a.owner(refs[0]).?;
        const owner_b = b.owner(refs[0]).?;
        try std.testing.expect(owner_a.terminal_ref.eql(owner_b.terminal_ref));
        try std.testing.expect(owner_a.generation.sameReplica(owner_b.generation));
        try std.testing.expect(owner_a.source_context != owner_b.source_context);
        return .{ .engine = engine, .a = a, .b = b, .owner_a = owner_a, .owner_b = owner_b };
    }

    fn select(remote: *support.PhuxProvider, owner: contract.ReplicaOwner) !State {
        const start = try remote.createAnchor(owner, .{ .space = .viewport, .row = 0, .column = 0 });
        const end = try remote.createAnchor(owner, .{ .space = .viewport, .row = 0, .column = 4 });
        try remote.setSelection(owner, start, end, false);
        const text = try remote.selectionText(owner, std.testing.allocator);
        defer std.testing.allocator.free(text);
        try std.testing.expect(text.len != 0);
        return .{ .owner = owner, .selecting = true, .start_anchor = start.opaque_id, .end_anchor = end.opaque_id };
    }

    fn expectSelection(remote: *support.PhuxProvider, owner: contract.ReplicaOwner, present: bool) !void {
        try std.testing.expect(remote.ownerIsCurrent(owner));
        try std.testing.expectEqual(present, remote.presentation(owner.terminal_ref).?.grid.selection_active);
        const text = remote.selectionText(owner, std.testing.allocator) catch |err| switch (err) {
            // FFI selection_text reports InvalidState for no active selection.
            // Prove the owner is still live and the published range is absent
            // above, so a stale-owner rejection cannot satisfy this assertion.
            error.InvalidState => return std.testing.expect(!present),
            else => return err,
        };
        defer std.testing.allocator.free(text);
        try std.testing.expectEqual(present, text.len != 0);
    }

    pub fn seedUi(self: SourceFixture) void {
        self.engine.model.remote_ui[0] = .{ .terminal_ref = self.owner_a.terminal_ref, .owner = self.owner_a, .selecting = true };
        self.engine.model.remote_ui[1] = .{ .terminal_ref = self.owner_b.terminal_ref, .owner = self.owner_b, .selecting = true };
        self.a.bridge.outgoing.reset();
        self.b.bridge.outgoing.reset();
    }

    fn queuedBytes(remote: *support.PhuxProvider) usize {
        var bytes: usize = 0;
        while (remote.bridge.outgoing.take()) |frame| {
            bytes += frame.len;
            remote.bridge.outgoing.release(frame);
        }
        return bytes;
    }
};

test "clear presentation resolves the captured client when endpoint ref and generation collide" {
    if (comptime !support.phux_enabled) return error.SkipZigTest;
    const fixture = try SourceFixture.init();
    defer fixture.engine.destroy();
    _ = try SourceFixture.select(fixture.a, fixture.owner_a);
    var state = try SourceFixture.select(fixture.b, fixture.owner_b);
    try std.testing.expect(clear(fixture.engine.model, &state));
    try SourceFixture.expectSelection(fixture.a, fixture.owner_a, true);
    try SourceFixture.expectSelection(fixture.b, fixture.owner_b, false);
}

test "selection release resolves the captured client and leaves sibling selection intact" {
    if (comptime !support.phux_enabled) return error.SkipZigTest;
    const fixture = try SourceFixture.init();
    defer fixture.engine.destroy();
    _ = try SourceFixture.select(fixture.a, fixture.owner_a);
    var state = try SourceFixture.select(fixture.b, fixture.owner_b);
    selection.clear(fixture.engine.model, &state);
    try SourceFixture.expectSelection(fixture.b, fixture.owner_b, false);
    try SourceFixture.expectSelection(fixture.a, fixture.owner_a, true);
}

test "clipboard completion keeps its captured source for text and UI state" {
    if (comptime !support.phux_enabled) return error.SkipZigTest;
    const fixture = try SourceFixture.init();
    defer fixture.engine.destroy();
    fixture.seedUi();
    const model = fixture.engine.model;
    model.copy_owner = fixture.owner_b;
    model.copy_inflight = true;
    interaction.copied(model, true);
    try std.testing.expect(model.remote_ui[0].selecting);
    try std.testing.expect(!model.remote_ui[1].selecting);
    model.paste_owner = fixture.owner_b;
    model.paste_inflight = true;
    const fx = @import("ts_engine.zig").NoShells{};
    interaction.pasted(model, &fx, true, "captured-b");
    try std.testing.expect(!model.paste_failed);
    try std.testing.expectEqual(@as(usize, 0), SourceFixture.queuedBytes(fixture.a));
    try std.testing.expect(SourceFixture.queuedBytes(fixture.b) > 0);
}

test "search clipboard completion changes only the captured source query" {
    if (comptime !support.phux_enabled) return error.SkipZigTest;
    const fixture = try SourceFixture.init();
    defer fixture.engine.destroy();
    fixture.seedUi();
    const model = fixture.engine.model;
    model.remote_ui[0].search = .{ .open = true, .paste_pending = true };
    model.remote_ui[1].search = .{ .open = true, .paste_pending = true };
    model.paste_owner = fixture.owner_b;
    model.paste_target = .search_needle;
    model.paste_inflight = true;
    const fx = @import("ts_engine.zig").NoShells{};
    interaction.pasted(model, &fx, true, "hello");
    try std.testing.expectEqualStrings("", model.remote_ui[0].search.needle());
    try std.testing.expect(model.remote_ui[0].search.paste_pending);
    try std.testing.expectEqualStrings("hello", model.remote_ui[1].search.needle());
    try std.testing.expect(!model.remote_ui[1].search.paste_pending);
    try std.testing.expect(!model.remote_ui[1].search.failed);
}

test "retired clipboard source never falls back to the matching live client" {
    if (comptime !support.phux_enabled) return error.SkipZigTest;
    const fixture = try SourceFixture.init();
    defer fixture.engine.destroy();
    fixture.seedUi();
    const model = fixture.engine.model;
    model.paste_owner = fixture.owner_b;
    model.paste_inflight = true;
    model.peers.items[0].provider = null;
    defer model.peers.items[0].provider = fixture.b;
    const fx = @import("ts_engine.zig").NoShells{};
    interaction.pasted(model, &fx, true, "must-not-send");
    try std.testing.expectEqual(@as(usize, 0), SourceFixture.queuedBytes(fixture.a));
    try std.testing.expectEqual(@as(usize, 0), SourceFixture.queuedBytes(fixture.b));
}
