//! Client presentation commands over the provider's Ghostty document API.
//! Search results stay owned by the host and are reacquired for navigation:
//! another pane's search or a replica replacement cannot leave borrowed handles
//! in UI state. No terminal input is generated by a presentation command.
const std = @import("std");
const native_sdk = @import("native_sdk");
const contract = @import("provider_contract");
const model_module = @import("../model.zig");
const support = @import("../phux_support.zig");
const interaction = @import("../terminal_interaction.zig");
const selection = @import("../update.zig").remote_selection;
const keyIs = @import("../terminal_runtime.zig").keyIs;
const Command = @import("ts_protocol.zig").NativeCommand;
const Model = model_module.Model;
const State = model_module.RemoteUiState;
const Step = enum { newest, older, newer, current };

pub const Search = struct {
    open: bool = false,
    needle_buf: [@import("../../terminal/session.zig").max_search_needle_bytes]u8 = undefined,
    needle_len: usize = 0,
    count: usize = 0,
    index: usize = 0,
    failed: bool = false,
    paste_pending: bool = false,
    restore_bottom: bool = true,
    restore_row: u64 = 0,

    pub fn needle(self: *const Search) []const u8 {
        return self.needle_buf[0..self.needle_len];
    }
};

pub fn command(model: *Model, ref: contract.TerminalRef, value: Command) bool {
    if (comptime !support.phux_enabled) return false;
    const state = model.remoteUi(ref) orelse return false;
    if (!model.ownerIsCurrent(state.owner)) return false;
    switch (value) {
        .find => return open(model, ref, state),
        .select_all => return selectAll(model, ref, state),
        .find_next, .find_previous => return refresh(model, state, if (value == .find_next) .older else .newer),
        .clear => return clear(model, state),
        else => return false,
    }
}

fn clear(model: *Model, state: *State) bool {
    const remote = model.phux() orelse return false;
    remote.clearPresentation(state.owner) catch return false;
    state.selecting = false;
    state.start_anchor = 0;
    state.end_anchor = 0;
    // Keep an open field and its needle, like local Clear, but retire every
    // result and pending field paste that belonged to the erased document.
    state.search.count = 0;
    state.search.index = 0;
    state.search.failed = false;
    state.search.paste_pending = false;
    state.search.restore_bottom = true;
    state.search.restore_row = 0;
    return true;
}

fn open(model: *Model, ref: contract.TerminalRef, state: *State) bool {
    if (state.search.open) return true;
    const view = model.remotePresentation(ref) orelse return false;
    state.search.restore_bottom = view.history_viewport_offset + view.history_visible_rows >= view.history_total_rows;
    state.search.restore_row = view.history_viewport_offset;
    selection.clear(model, state);
    state.search.open = true;
    return true;
}

fn selectAll(model: *Model, ref: contract.TerminalRef, state: *State) bool {
    const view = model.remotePresentation(ref) orelse return false;
    const total = view.history_total_rows;
    const cols = view.cols;
    if (total == 0 or cols == 0 or total > std.math.maxInt(u32)) return false;
    const remote = model.phux() orelse return false;
    const start = remote.createAnchor(state.owner, .{ .space = .history, .row = 0, .column = 0 }) catch return false;
    const end = remote.createAnchor(state.owner, .{ .space = .history, .row = @intCast(total - 1), .column = cols - 1 }) catch {
        remote.releaseAnchor(state.owner, start);
        return false;
    };
    selection.clear(model, state);
    remote.setSelection(state.owner, start, end, false) catch {
        remote.releaseAnchor(state.owner, start);
        remote.releaseAnchor(state.owner, end);
        return false;
    };
    state.start_anchor = start.opaque_id;
    state.end_anchor = end.opaque_id;
    state.selecting = false;
    return true;
}

pub fn close(model: *Model, state: *State) void {
    if (comptime !support.phux_enabled) return;
    const remote = model.phux() orelse return;
    remote.clearSearchResults(state.owner);
    selection.clear(model, state);
    if (state.search.restore_bottom) {
        remote.scrollViewport(state.owner, .{ .kind = .bottom }) catch {};
    } else {
        remote.scrollViewport(state.owner, .{ .kind = .top }) catch {};
        remote.scrollViewport(state.owner, .{ .kind = .delta, .value = @intCast(state.search.restore_row) }) catch {};
    }
    state.search = .{};
}

/// A navigation command reruns the provider query before using its anchors.
/// Copy the chosen result before pin/setSelection invalidate borrowed arrays.
fn refresh(model: *Model, state: *State, step: Step) bool {
    if (comptime !support.phux_enabled) return false;
    if (!state.search.open) return false;
    const remote = model.phux() orelse return false;
    state.search.failed = false;
    selection.clear(model, state);
    if (state.search.needle_len == 0) {
        remote.clearSearchResults(state.owner);
        state.search.count = 0;
        return true;
    }
    const results = remote.search(state.owner, state.search.needle()) catch {
        return failSearch(remote, state);
    };
    state.search.count = results.len;
    if (results.len == 0) return true;
    state.search.index = nextIndex(state.search.index, results.len, step);
    const result = results[state.search.index];
    return reveal(remote, state, result);
}

fn reveal(remote: *support.PhuxProvider, state: *State, result: anytype) bool {
    remote.pinViewport(state.owner, result.start) catch return failSearch(remote, state);
    remote.setSelection(state.owner, result.start, result.end, false) catch return failSearch(remote, state);
    return true;
}

fn failSearch(remote: *support.PhuxProvider, state: *State) bool {
    state.search.failed = true;
    state.search.count = 0;
    remote.clearSelection(state.owner) catch {};
    return false;
}

fn nextIndex(previous: usize, count: usize, step: Step) usize {
    const current = @min(previous, count - 1);
    // Find Next follows the local search: older matches, wrapping at the top.
    return switch (step) {
        .newest => count - 1,
        .older => (current + count - 1) % count,
        .newer => (current + 1) % count,
        .current => current,
    };
}

pub fn prepareCopy(model: *Model, state: *State) bool {
    if (!state.search.open) return true;
    return refresh(model, state, .current);
}

pub fn input(model: *Model, ref: contract.TerminalRef, text: []const u8) bool {
    const state = model.remoteUi(ref) orelse return false;
    if (!state.search.open or text.len == 0) return false;
    if (!std.unicode.utf8ValidateSlice(text)) return false;
    for (text) |byte| if (byte < 0x20 or byte == 0x7f) return false;
    if (text.len > state.search.needle_buf.len - state.search.needle_len) return false;
    @memcpy(state.search.needle_buf[state.search.needle_len..][0..text.len], text);
    state.search.needle_len += text.len;
    return refresh(model, state, .newest);
}

pub fn paste(model: *Model, ref: contract.TerminalRef, text: []const u8) bool {
    const state = model.remoteUi(ref) orelse return false;
    if (!state.search.open) return false;
    var filtered: [@import("../../terminal/session.zig").max_search_needle_bytes]u8 = undefined;
    const len = pasteLine(text, filtered[0 .. filtered.len - state.search.needle_len]);
    return input(model, ref, filtered[0..len]);
}

fn pasteLine(text: []const u8, filtered: []u8) usize {
    var len: usize = 0;
    for (text) |byte| {
        if (byte == '\n' or byte == '\r') break;
        if (byte < 0x20 or byte == 0x7f) continue;
        if (len == filtered.len) break;
        filtered[len] = byte;
        len += 1;
    }
    // A bounded paste must never leave half of a UTF-8 scalar in the field.
    while (len > 0 and !std.unicode.utf8ValidateSlice(filtered[0..len])) len -= 1;
    return len;
}

pub fn key(model: *Model, fx: anytype, ref: contract.TerminalRef, event: native_sdk.canvas.WidgetKeyboardEvent) void {
    const state = model.remoteUi(ref) orelse return;
    if (event.modifiers.super and !event.modifiers.control) {
        if (keyIs(event.key, "v")) return interaction.requestPaste(model, fx, ref);
        if (keyIs(event.key, "c")) return interaction.copy(model, fx, ref);
        if (keyIs(event.key, "g")) {
            _ = refresh(model, state, if (event.modifiers.shift) .newer else .older);
            return;
        }
    }
    editKey(model, state, event);
}

fn editKey(model: *Model, state: *State, event: native_sdk.canvas.WidgetKeyboardEvent) void {
    if (keyIs(event.key, "escape")) return close(model, state);
    if (keyIs(event.key, "enter") or keyIs(event.key, "return")) {
        _ = refresh(model, state, if (event.modifiers.shift) .newer else .older);
        return;
    }
    if (!keyIs(event.key, "backspace") and !keyIs(event.key, "delete")) return;
    if (state.search.needle_len == 0) return;
    var end = state.search.needle_len - 1;
    while (end > 0 and state.search.needle_buf[end] & 0xc0 == 0x80) end -= 1;
    state.search.needle_len = end;
    _ = refresh(model, state, .newest);
}
