// Generated by scripts/command-catalog.mjs from app.zon.
import { asciiBytes, utf8Bytes } from "@native-sdk/core";

export interface CommandDefinition {
  readonly index: number;
  readonly name: string;
  readonly label: Uint8Array;
  readonly shortcut: Uint8Array;
}

export const COMMAND_CATALOG: readonly CommandDefinition[] = [
  { index: 0, name: "window.new", label: utf8Bytes("New Window"), shortcut: asciiBytes("Cmd+N") },
  { index: 1, name: "terminal.new", label: utf8Bytes("New Tab"), shortcut: asciiBytes("Cmd+T") },
  { index: 2, name: "session.new", label: utf8Bytes("New Session"), shortcut: asciiBytes("") },
  { index: 3, name: "pane.split-right", label: utf8Bytes("Split Right"), shortcut: asciiBytes("Cmd+D") },
  { index: 4, name: "pane.split-down", label: utf8Bytes("Split Down"), shortcut: asciiBytes("Cmd+Shift+D") },
  { index: 5, name: "terminal.close", label: utf8Bytes("Close Pane"), shortcut: asciiBytes("Cmd+W") },
  { index: 6, name: "terminal.copy", label: utf8Bytes("Copy"), shortcut: asciiBytes("Cmd+C") },
  { index: 7, name: "terminal.paste", label: utf8Bytes("Paste"), shortcut: asciiBytes("Cmd+V") },
  { index: 8, name: "terminal.select-all", label: utf8Bytes("Select All"), shortcut: asciiBytes("Cmd+A") },
  { index: 9, name: "terminal.clear", label: utf8Bytes("Clear"), shortcut: asciiBytes("Cmd+K") },
  { index: 10, name: "terminal.find", label: utf8Bytes("Find"), shortcut: asciiBytes("Cmd+F") },
  { index: 11, name: "terminal.find-next", label: utf8Bytes("Find Next"), shortcut: asciiBytes("Cmd+G") },
  { index: 12, name: "terminal.find-previous", label: utf8Bytes("Find Previous"), shortcut: asciiBytes("Cmd+Shift+G") },
  { index: 13, name: "commands.open", label: utf8Bytes("Commands"), shortcut: asciiBytes("Cmd+Shift+P") },
  { index: 14, name: "settings.open", label: utf8Bytes("Settings"), shortcut: asciiBytes("Cmd+,") },
  { index: 15, name: "config.edit", label: utf8Bytes("Edit Configuration"), shortcut: asciiBytes("") },
  { index: 16, name: "window.fullscreen", label: utf8Bytes("Enter Full Screen"), shortcut: asciiBytes("Cmd+Ctrl+F") },
  { index: 17, name: "view.font-larger", label: utf8Bytes("Increase Font Size"), shortcut: asciiBytes("Cmd+=") },
  { index: 18, name: "view.font-smaller", label: utf8Bytes("Decrease Font Size"), shortcut: asciiBytes("Cmd+-") },
  { index: 19, name: "view.font-reset", label: utf8Bytes("Reset Font Size"), shortcut: asciiBytes("Cmd+0") },
  { index: 20, name: "tabs.toggle-placement", label: utf8Bytes("Toggle Tab Placement"), shortcut: asciiBytes("") },
  { index: 21, name: "window.minimize", label: utf8Bytes("Minimize"), shortcut: asciiBytes("Cmd+M") },
  { index: 22, name: "navigator.sessions", label: utf8Bytes("Sessions"), shortcut: asciiBytes("") },
  { index: 23, name: "navigator.machines", label: utf8Bytes("Machines"), shortcut: asciiBytes("Cmd+Shift+O") },
  { index: 24, name: "navigator.windows", label: utf8Bytes("Show All Windows"), shortcut: asciiBytes("") },
  { index: 25, name: "tabs.palette", label: utf8Bytes("Go to Terminal"), shortcut: asciiBytes("") },
  { index: 26, name: "directory.open", label: utf8Bytes("Go to Directory"), shortcut: asciiBytes("Cmd+Shift+J") },
  { index: 27, name: "session.rename", label: utf8Bytes("Rename Session"), shortcut: asciiBytes("") },
  { index: 28, name: "tab.previous", label: utf8Bytes("Previous Tab"), shortcut: asciiBytes("Cmd+Shift+[") },
  { index: 29, name: "tab.next", label: utf8Bytes("Next Tab"), shortcut: asciiBytes("Cmd+Shift+]") },
  { index: 30, name: "tab.move-left", label: utf8Bytes("Move Tab Left"), shortcut: asciiBytes("Cmd+Shift+Left") },
  { index: 31, name: "tab.move-right", label: utf8Bytes("Move Tab Right"), shortcut: asciiBytes("Cmd+Shift+Right") },
  { index: 32, name: "pane.previous", label: utf8Bytes("Previous Pane"), shortcut: asciiBytes("Cmd+[") },
  { index: 33, name: "pane.next", label: utf8Bytes("Next Pane"), shortcut: asciiBytes("Cmd+]") },
];
