// Fumadocs source adapter. Bridges the Astro content collections (which the
// sync-docs pipeline generates into src/content/docs/_synced/) onto the
// Fumadocs loader, so the docs pages get the page tree, sidebar, TOC, search,
// and prev/next from Fumadocs instead of the old hand-rolled chrome.
import { loader } from "fumadocs-core/source";
import { type CollectionEntry, getCollection } from "astro:content";
import * as path from "node:path";

// Content root — everything in _synced/ is generated by scripts/sync-docs.ts.
const SYNCED_ROOT = "src/content/docs/_synced";

export const source = loader({
  source: await createMySource(),
  baseUrl: "/",
});

async function createMySource() {
  const out: StaticSource = { files: [] };

  // Page paths are the *file paths* relative to the content root (e.g.
  // "quickstart/index.md", "wire/l1.md") so Fumadocs builds the folder tree
  // with section READMEs as folder indexes — matching the site's URLs exactly.
  for (const page of await getCollection("docs")) {
    const filePath = path.relative(SYNCED_ROOT, page.filePath!).split(/[\\/]/).join("/");
    out.files.push({
      type: "page",
      path: filePath,
      data: {
        ...page.data,
        _raw: page,
      },
    });
  }

  for (const meta of await getCollection("meta")) {
    const filePath = path.relative(SYNCED_ROOT, meta.filePath!).split(/[\\/]/).join("/");
    out.files.push({
      type: "meta",
      path: filePath,
      data: meta.data,
    });
  }

  return out;
}

interface StaticSource {
  files: (
    | {
        type: "page";
        path: string;
        data: CollectionEntry<"docs">["data"] & {
          _raw: CollectionEntry<"docs">;
        };
      }
    | {
        type: "meta";
        path: string;
        data: CollectionEntry<"meta">["data"];
      }
  )[];
}
