#!/usr/bin/env bash
# check-docs.sh
#
# Doc-system gates for the phux repository. Enforces the contract laid
# out in docs/CONVENTIONS.md (the "discipline" layer of the doc tree).
#
# Gates:
#   - frontmatter-present : every checked .md has a YAML header with
#                           audience/stability/last-reviewed
#   - frontmatter-valid   : that header's values match the controlled
#                           vocabulary
#   - tldr-present        : first non-frontmatter / non-H1 paragraph
#                           begins with "**TL;DR.**"
#   - dead-link           : every relative `[text](path.md...)` link
#                           resolves to a real file
#   - adr-status          : every ADR's `Status:` line is one of the
#                           four blessed forms
#   - adr-number-unique   : no two files under ADR/ share the same
#                           leading NNNN number
#   - adr-index-sync      : every ADR/NNNN-*.md has exactly one row in
#                           ADR/README.md's index, every row resolves to
#                           its file, and rows ascend numerically
#   - spec-version-sync   : docs/spec/CHANGELOG.md head version agrees
#                           with phux-protocol's PROTOCOL_VERSION
#                           (skipped while the SPEC split is in flight)
#   - impl-status         : every shipped/partial/spec-only claim in
#                           docs/spec/ and docs/consumers/ agrees with
#                           the code it names
#
# Usage:
#   bash scripts/check-docs.sh             # run all gates
#   bash scripts/check-docs.sh --help
#   bash scripts/check-docs.sh --list
#   bash scripts/check-docs.sh --only=tldr-present
#
# Exit codes:
#   0   no violations
#   1   one or more violations
#   2   script invoked incorrectly

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

ALL_GATES=(
    frontmatter-present
    frontmatter-valid
    tldr-present
    dead-link
    adr-status
    adr-number-unique
    adr-index-sync
    spec-version-sync
    impl-status
)

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

ONLY=""

usage() {
    cat <<'EOF'
check-docs.sh — mechanical enforcement for docs/CONVENTIONS.md

USAGE:
    bash scripts/check-docs.sh [--help] [--list] [--only=<gate>]

OPTIONS:
    --help          show this message and exit
    --list          print the gates this script implements and exit
    --only=<gate>   run only the named gate

Gates write violations to stderr prefixed with `[<gate-name>]`. The
script prints a `checked N files, M violations` summary on stdout and
exits 0 if M == 0, else 1.

See docs/CONVENTIONS.md for the contract these gates enforce.
EOF
}

list_gates() {
    echo "Gates implemented:"
    for g in "${ALL_GATES[@]}"; do
        echo "  - $g"
    done
}

for arg in "$@"; do
    case "$arg" in
        --help|-h)
            usage
            exit 0
            ;;
        --list)
            list_gates
            exit 0
            ;;
        --only=*)
            ONLY="${arg#--only=}"
            ;;
        *)
            echo "error: unknown argument: $arg" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -n "$ONLY" ]]; then
    found=0
    for g in "${ALL_GATES[@]}"; do
        if [[ "$g" == "$ONLY" ]]; then
            found=1
            break
        fi
    done
    if [[ "$found" -eq 0 ]]; then
        echo "error: --only=$ONLY does not match a known gate" >&2
        list_gates >&2
        exit 2
    fi
fi

should_run() {
    local gate="$1"
    [[ -z "$ONLY" || "$ONLY" == "$gate" ]]
}

# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

# Build the list of .md files we care about. Exclusions, per CONVENTIONS.md:
#   - LICENSE* (not markdown anyway, but defensive)
#   - .beads/, .direnv/, .git/, target/, research/archive/
#   - crates/*/tests/*/README.md (test fixtures, not part of the doc system)
# Inclusions:
#   - everything under docs/ and ADR/
#   - top-level .md (README, AGENTS, CLAUDE, CONTRIBUTING, ARCHITECTURE,
#     SPEC, DESIGN, VISION)
#   - research/ (excluding research/archive/) — `stability: scratch`
#     lives here and CONVENTIONS.md says frontmatter is still required.

collect_files() {
    # Top-level .md files.
    #
    # CHANGELOG.md is exempt: it is generated by release-please from the
    # conventional-commit log and rewritten on every release. It has no
    # author to carry frontmatter, and a `**TL;DR.**` block would be
    # clobbered on the next release anyway. Note this exclusion is scoped
    # to the repo root — docs/spec/CHANGELOG.md (the normative wire log,
    # hand-maintained) is collected by the docs/ sweep below and keeps
    # every gate.
    find "$ROOT" -maxdepth 1 -type f -name '*.md' \
        ! -iname 'LICENSE*' \
        ! -name 'CHANGELOG.md' \
        -print
    # docs/ tree.
    if [[ -d "$ROOT/docs" ]]; then
        find "$ROOT/docs" -type f -name '*.md' -print
    fi
    # ADR/ tree.
    if [[ -d "$ROOT/ADR" ]]; then
        find "$ROOT/ADR" -type f -name '*.md' -print
    fi
    # research/, minus archive/.
    if [[ -d "$ROOT/research" ]]; then
        find "$ROOT/research" -type f -name '*.md' \
            -not -path "$ROOT/research/archive/*" \
            -print
    fi
}

FILES=()
while IFS= read -r f; do
    [[ -n "$f" ]] && FILES+=("$f")
done < <(collect_files | LC_ALL=C sort -u)

# The ADR corpus proper, sorted: every file under ADR/ whose basename opens
# with a four-digit number (`NNNN-slug.md`).
#
# One definition, because three gates need it and each used to carry its own
# basename test — so "what counts as an ADR file" had three answers that only
# happened to agree. Everything else under ADR/ (the README index, companion
# documents such as a ratification brief) carries no decision and no ADR
# number: it must not be given a `Status:` line, cannot claim a number, and
# has no index row. Those files still keep every gate in `collect_files`,
# which sweeps ADR/ whole.
adr_files() {
    if [[ ! -d "$ROOT/ADR" ]]; then
        return
    fi
    find "$ROOT/ADR" -type f -name '[0-9][0-9][0-9][0-9]-*.md' | LC_ALL=C sort
}

# ---------------------------------------------------------------------------
# Violation bookkeeping
# ---------------------------------------------------------------------------

VIOLATIONS=0

violate() {
    # violate <gate> <file> <message...>
    local gate="$1"
    local file="$2"
    shift 2
    local rel="${file#$ROOT/}"
    echo "[$gate] $rel: $*" >&2
    VIOLATIONS=$((VIOLATIONS + 1))
}

# ---------------------------------------------------------------------------
# Frontmatter parsing helpers
# ---------------------------------------------------------------------------

# Echoes the line number (1-based) of the closing `---` if the file opens
# with a YAML frontmatter block within the first 20 lines, else nothing.
frontmatter_close_line() {
    local file="$1"
    awk 'NR == 1 { if ($0 != "---") exit 0 }
         NR > 1 && NR <= 20 { if ($0 == "---") { print NR; exit 0 } }
         NR > 20 { exit 0 }' "$file"
}

# Echoes the value (everything after `key:`) for a frontmatter key, trimmed.
# Only looks inside the frontmatter block (lines 2..close-1).
# (awk's `close` is a builtin, so the variable is named `close_line`.)
frontmatter_value() {
    local file="$1"
    local key="$2"
    local close_line="$3"
    awk -v key="$key" -v close_line="$close_line" '
        NR >= 2 && NR < close_line {
            if (match($0, "^[[:space:]]*" key ":[[:space:]]*")) {
                v = substr($0, RLENGTH + 1)
                gsub(/[[:space:]]+$/, "", v)
                print v
                exit
            }
        }
    ' "$file"
}

# Is this the repo-root README.md? It is exempt from YAML frontmatter
# (would render visibly on GitHub as the project landing page) and
# from the TL;DR gate (the README's whole job is to be the landing
# page, not to summarize itself). Instead, it declares the same
# metadata via an opening HTML comment block within the first 20
# lines. See docs/CONVENTIONS.md.
is_root_readme() {
    [[ "$1" == "$ROOT/README.md" ]]
}

# For the README only: echoes the closing-comment line if an HTML
# comment block opens on line 1 and closes within the first 20 lines.
readme_html_close_line() {
    local file="$1"
    awk 'NR == 1 { if ($0 != "<!--") exit 0 }
         NR > 1 && NR <= 20 { if ($0 ~ /-->[[:space:]]*$/) { print NR; exit 0 } }
         NR > 20 { exit 0 }' "$file"
}

# ---------------------------------------------------------------------------
# Gate 1: frontmatter-present
# ---------------------------------------------------------------------------

gate_frontmatter_present() {
    local file close
    for file in "${FILES[@]}"; do
        # README.md exception: HTML-comment metadata in place of YAML.
        if is_root_readme "$file"; then
            close="$(readme_html_close_line "$file" || true)"
            if [[ -z "$close" ]]; then
                violate frontmatter-present "$file" \
                    "missing or malformed HTML-comment metadata (need '<!--' on line 1 and '-->' within the first 20 lines; README is exempt from YAML frontmatter — see docs/CONVENTIONS.md)"
                continue
            fi
            local rmissing=()
            for key in audience stability last-reviewed; do
                if ! awk -v key="$key" -v close_line="$close" '
                        NR >= 2 && NR < close_line {
                            if (match($0, "^[[:space:]]*" key ":[[:space:]]*[^[:space:]]")) { found = 1; exit }
                        }
                        END { exit (found ? 0 : 1) }
                    ' "$file"; then
                    rmissing+=("$key")
                fi
            done
            if (( ${#rmissing[@]} > 0 )); then
                violate frontmatter-present "$file" \
                    "HTML-comment metadata missing key(s): ${rmissing[*]}"
            fi
            continue
        fi

        close="$(frontmatter_close_line "$file" || true)"
        if [[ -z "$close" ]]; then
            violate frontmatter-present "$file" \
                "missing or malformed YAML frontmatter (need '---' on line 1 and a closing '---' within the first 20 lines)"
            continue
        fi
        local missing=()
        for key in audience stability last-reviewed; do
            local val
            val="$(frontmatter_value "$file" "$key" "$close" || true)"
            if [[ -z "$val" ]]; then
                missing+=("$key")
            fi
        done
        if (( ${#missing[@]} > 0 )); then
            violate frontmatter-present "$file" \
                "frontmatter missing key(s): ${missing[*]}"
        fi
    done
}

# ---------------------------------------------------------------------------
# Gate 2: frontmatter-valid
# ---------------------------------------------------------------------------

# Allowed sets.
AUDIENCE_ALLOWED='^(humans|agents|consumers|contributors)$'
STABILITY_ALLOWED='^(stable|evolving|scratch)$'
DATE_RE='^[0-9]{4}-[0-9]{2}-[0-9]{2}$'

gate_frontmatter_valid() {
    local file close
    for file in "${FILES[@]}"; do
        close="$(frontmatter_close_line "$file" || true)"
        # If there's no frontmatter, gate 1 already complained; skip here.
        [[ -z "$close" ]] && continue

        local audience stability reviewed
        audience="$(frontmatter_value "$file" "audience" "$close" || true)"
        stability="$(frontmatter_value "$file" "stability" "$close" || true)"
        reviewed="$(frontmatter_value "$file" "last-reviewed" "$close" || true)"

        # audience: comma-separated list of allowed words.
        if [[ -n "$audience" ]]; then
            local cleaned
            cleaned="$(echo "$audience" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            local bad=""
            while IFS= read -r token; do
                [[ -z "$token" ]] && continue
                if ! [[ "$token" =~ $AUDIENCE_ALLOWED ]]; then
                    bad+="${bad:+, }$token"
                fi
            done <<< "$cleaned"
            if [[ -n "$bad" ]]; then
                violate frontmatter-valid "$file" \
                    "audience: invalid value(s): $bad (allowed: humans, agents, consumers, contributors)"
            fi
        fi

        # stability: single word from the allowed set.
        if [[ -n "$stability" ]]; then
            if ! [[ "$stability" =~ $STABILITY_ALLOWED ]]; then
                violate frontmatter-valid "$file" \
                    "stability: invalid value '$stability' (allowed: stable, evolving, scratch)"
            fi
        fi

        # last-reviewed: ISO date.
        if [[ -n "$reviewed" ]]; then
            if ! [[ "$reviewed" =~ $DATE_RE ]]; then
                violate frontmatter-valid "$file" \
                    "last-reviewed: '$reviewed' is not a YYYY-MM-DD date"
            fi
        fi
    done
}

# ---------------------------------------------------------------------------
# Gate 3: tldr-present
# ---------------------------------------------------------------------------

# Per CONVENTIONS.md: the first non-blank, non-frontmatter, non-H1 line
# of content must start with `**TL;DR.**`. We tolerate any number of
# blank lines between the H1 and the TL;DR, and we treat the absence of
# a frontmatter block as "skip" — gate 1 already flagged that case.

gate_tldr_present() {
    local file close
    for file in "${FILES[@]}"; do
        # README.md is exempt — its whole job is to be the landing page;
        # a TL;DR paragraph would degrade that. See docs/CONVENTIONS.md.
        if is_root_readme "$file"; then
            continue
        fi
        close="$(frontmatter_close_line "$file" || true)"
        local start=1
        if [[ -n "$close" ]]; then
            start=$((close + 1))
        fi
        local result
        result="$(awk -v start="$start" '
            NR < start { next }
            {
                # strip CR
                sub(/\r$/, "")
                # skip blank lines
                if ($0 ~ /^[[:space:]]*$/) next
                # skip a single H1 (first non-blank H1 only)
                if (!seen_h1 && $0 ~ /^#[[:space:]]/) {
                    seen_h1 = 1
                    next
                }
                # first non-blank, non-H1 line of content.
                if ($0 ~ /^\*\*TL;DR\.\*\*/) {
                    print "ok"
                } else {
                    print "bad:" $0
                }
                printed = 1
                exit
            }
            END {
                if (!printed) print "empty"
            }
        ' "$file" || true)"
        case "$result" in
            ok) ;;
            bad:*)
                violate tldr-present "$file" \
                    "first content line is not a '**TL;DR.**' paragraph (saw: ${result#bad:})"
                ;;
            empty|"")
                violate tldr-present "$file" \
                    "no content found after frontmatter (need an H1 and a '**TL;DR.**' paragraph)"
                ;;
        esac
    done
}

# ---------------------------------------------------------------------------
# Gate 4: dead-link
# ---------------------------------------------------------------------------

# Match `[text](path)` where `path` does not start with a scheme
# (http://, https://, mailto:, #...) and is not absolute (`/...`).
# Anchors (`#...`) on the end are stripped before resolving.

gate_dead_link() {
    local file
    for file in "${FILES[@]}"; do
        local dir
        dir="$(dirname "$file")"
        # Extract every `](...)` target. We use grep -oE then awk-clean.
        # The regex purposely keeps it simple: balanced parens inside the
        # URL aren't supported (markdown's spec discourages them anyway).
        while IFS= read -r link; do
            [[ -z "$link" ]] && continue
            # Skip absolute URLs.
            case "$link" in
                http://*|https://*|mailto:*|ftp://*|tel:*|ws://*|wss://*)
                    continue ;;
                '#'*)
                    # Pure in-page anchor — nothing to resolve.
                    continue ;;
                /*)
                    # Repo-absolute or filesystem-absolute. Resolve from
                    # repo root rather than treating it as filesystem-/.
                    : ;;
            esac

            # Strip anchor and optional query.
            local target="${link%%#*}"
            target="${target%%\?*}"
            [[ -z "$target" ]] && continue

            local resolved
            case "$target" in
                /*)
                    resolved="$ROOT$target"
                    ;;
                *)
                    resolved="$dir/$target"
                    ;;
            esac

            if [[ ! -e "$resolved" ]]; then
                violate dead-link "$file" \
                    "broken relative link: $link"
            fi
        done < <(grep -oE '\]\([^)]+\)' "$file" 2>/dev/null \
                  | sed -E 's/^\]\(//; s/\)$//' \
                  | awk '{print $1}')
        # ^ awk {print $1} strips any optional title `](path "title")`.
    done
}

# ---------------------------------------------------------------------------
# Gate 5: adr-status
# ---------------------------------------------------------------------------

# Allowed statuses (anchored, exact):
#   Status: Proposed
#   Status: Accepted
#   Status: Accepted (forward-compat)
#   Status: Superseded by ADR-NNNN
#   Status: Deprecated

gate_adr_status() {
    local file
    if [[ ! -d "$ROOT/ADR" ]]; then
        return
    fi
    # `adr_files` is what "an ADR" means here: the README index and companion
    # documents carry no decision and must not be given a `Status:` line,
    # since that vocabulary means "the repository has decided".
    while IFS= read -r file; do
        local close
        close="$(frontmatter_close_line "$file" || true)"
        local start=1
        [[ -n "$close" ]] && start=$((close + 1))

        # First `Status:` line outside frontmatter.
        local status_line
        status_line="$(awk -v start="$start" '
            NR < start { next }
            /^Status:/ { sub(/\r$/, ""); print; exit }
        ' "$file" || true)"

        if [[ -z "$status_line" ]]; then
            violate adr-status "$file" "no 'Status:' line found"
            continue
        fi

        case "$status_line" in
            "Status: Proposed"|\
            "Status: Accepted"|\
            "Status: Accepted (forward-compat)"|\
            "Status: Deprecated")
                ;;
            "Status: Superseded by ADR-"[0-9][0-9][0-9][0-9])
                ;;
            *)
                violate adr-status "$file" \
                    "non-vocabulary status: '$status_line' (allowed: 'Status: Proposed', 'Status: Accepted', 'Status: Accepted (forward-compat)', 'Status: Superseded by ADR-NNNN', 'Status: Deprecated')"
                ;;
        esac
    done < <(adr_files)
}

# ---------------------------------------------------------------------------
# Gate 5b: adr-number-unique
# ---------------------------------------------------------------------------

# Every ADR filename opens with a 4-digit number (NNNN-slug.md). That number
# is the identity readers and cross-references use ("ADR-NNNN") — two files
# sharing one make every such reference ambiguous, with no signal to the
# reader that they might have landed on the wrong decision. This gate fails
# if any number prefix under ADR/ is claimed by more than one file.

gate_adr_number_unique() {
    local file
    if [[ ! -d "$ROOT/ADR" ]]; then
        return
    fi

    local -A first_seen=()
    while IFS= read -r file; do
        # `adr_files` yields only `NNNN-slug.md`; this reads the number out of
        # the name rather than deciding again what counts as an ADR.
        [[ "$(basename "$file")" =~ ^([0-9]{4})- ]] || continue
        local num="${BASH_REMATCH[1]}"
        if [[ -n "${first_seen[$num]:-}" ]]; then
            violate adr-number-unique "$file" \
                "ADR number $num is also used by ${first_seen[$num]#"$ROOT"/} — renumber one of the two (pick whichever has fewer inbound references) to the next free ADR number, then update every 'ADR-$num' cross-reference (prose, markdown links, code comments) that meant the renumbered file"
        else
            first_seen[$num]="$file"
        fi
    done < <(adr_files)
}

# ---------------------------------------------------------------------------
# Gate 5c: adr-index-sync
# ---------------------------------------------------------------------------

# Every ADR has exactly one row in ADR/README.md's index, inserted at its
# numeric position. The row is deliberately a collision point for parallel
# branches: two branches that each claim the same ADR number either conflict
# textually on the index row at rebase, or — if the merge somehow slides
# through — fail here. Without the row, git sees two disjoint new files and
# reports zero conflicts (it happened: wave 3 produced two different
# ADR-0086 files, silently). Three checks, bidirectional:
#
#   1. every ADR/NNNN-*.md file has exactly one index row for its number
#   2. every index row's link resolves to a real file whose name starts
#      with the row's number
#   3. row numbers are strictly ascending down the table

gate_adr_index_sync() {
    if [[ ! -d "$ROOT/ADR" ]]; then
        return
    fi
    local readme="$ROOT/ADR/README.md"
    if [[ ! -f "$readme" ]]; then
        violate adr-index-sync "$readme" \
            "ADR/README.md not found — the ADR index is required"
        return
    fi

    # Collect index rows: `| [NNNN](./NNNN-slug.md) | ... |`.
    local line num target prev=""
    local -A row_target=()
    local row_re='^\|[[:space:]]*\[([0-9]{4})\]\(\./([^)]+)\)'
    while IFS= read -r line; do
        [[ "$line" =~ $row_re ]] || continue
        num="${BASH_REMATCH[1]}"
        target="${BASH_REMATCH[2]}"

        # A number already in `row_target` *is* the second-row signal; a
        # parallel counter said the same thing twice. The first row wins, so
        # the reverse direction below compares against the row a reader would
        # follow.
        if [[ -n "${row_target[$num]:-}" ]]; then
            violate adr-index-sync "$readme" \
                "index has more than one row for ADR number $num"
        else
            row_target[$num]="$target"
        fi

        if [[ ! -f "$ROOT/ADR/$target" ]]; then
            violate adr-index-sync "$readme" \
                "index row $num links to ./$target, which does not exist"
        elif [[ "$target" != "$num-"* ]]; then
            violate adr-index-sync "$readme" \
                "index row $num links to ./$target, whose filename does not start with $num-"
        fi

        if [[ -n "$prev" ]] && (( 10#$num <= 10#$prev )); then
            violate adr-index-sync "$readme" \
                "index row $num appears after row $prev — rows must ascend numerically (insert each new ADR's row at its numeric position)"
        fi
        prev="$num"
    done < "$readme"

    # Reverse direction: every ADR file has its row, and the row points at
    # this file (not at a same-numbered sibling — the duplicate-claim case
    # adr-number-unique also reports).
    local file base
    while IFS= read -r file; do
        base="$(basename "$file")"
        # Reads the number out of the name; `adr_files` decides membership.
        [[ "$base" =~ ^([0-9]{4})- ]] || continue
        num="${BASH_REMATCH[1]}"
        if [[ -z "${row_target[$num]:-}" ]]; then
            violate adr-index-sync "$file" \
                "no index row in ADR/README.md for ADR number $num — every ADR adds exactly one row at its numeric position (see the comment above the index)"
        elif [[ "${row_target[$num]}" != "$base" ]]; then
            violate adr-index-sync "$file" \
                "index row $num links to ./${row_target[$num]}, not to this file — two files are claiming the same ADR number, or the row was not updated with a rename"
        fi
    done < <(adr_files)
}

# ---------------------------------------------------------------------------
# Gate 6: spec-version-sync
# ---------------------------------------------------------------------------

# Compare the head version listed in docs/spec/CHANGELOG.md (first table
# row that starts with `| <version> |`) against the PROTOCOL_VERSION
# constant in crates/phux-protocol/src/lib.rs.
#
# CONVENTIONS.md notes the SPEC split is in flight; docs/spec/CHANGELOG.md
# does not yet exist. While that's true, this gate emits a single NOTE
# line and does nothing else — it activates automatically once the file
# appears.

gate_spec_version_sync() {
    local changelog="$ROOT/docs/spec/CHANGELOG.md"
    if [[ ! -f "$changelog" ]]; then
        echo "[spec-version-sync] NOTE: $changelog does not exist yet; gate is dormant until the SPEC split lands." >&2
        return
    fi

    # First table row: a line beginning with `| ` followed by a non-pipe
    # version token, then ` |`. We tolerate leading whitespace.
    local head_version
    head_version="$(awk '
        /^[[:space:]]*\|[[:space:]]*[^|[:space:]]+[[:space:]]*\|/ {
            # Strip leading `|` and surrounding whitespace.
            line = $0
            sub(/^[[:space:]]*\|[[:space:]]*/, "", line)
            # Token is everything up to the next `|`.
            n = index(line, "|")
            if (n > 0) {
                v = substr(line, 1, n - 1)
                sub(/[[:space:]]+$/, "", v)
                # Skip header / separator rows like `| Version |` or `|---|`.
                if (v ~ /^[-: ]+$/) next
                if (tolower(v) == "version") next
                print v
                exit
            }
        }
    ' "$changelog")"

    if [[ -z "$head_version" ]]; then
        violate spec-version-sync "$changelog" \
            "could not parse a head version from the first table row"
        return
    fi

    # Pull PROTOCOL_VERSION out of phux-protocol's lib.rs.
    local lib="$ROOT/crates/phux-protocol/src/lib.rs"
    if [[ ! -f "$lib" ]]; then
        violate spec-version-sync "$lib" \
            "crates/phux-protocol/src/lib.rs not found; cannot verify PROTOCOL_VERSION"
        return
    fi

    local major minor patch
    major="$(awk '/PROTOCOL_VERSION/{flag=1} flag && /major:/{gsub(/[^0-9]/,"",$0); print; exit}' "$lib")"
    minor="$(awk '/PROTOCOL_VERSION/{flag=1} flag && /minor:/{gsub(/[^0-9]/,"",$0); print; exit}' "$lib")"
    patch="$(awk '/PROTOCOL_VERSION/{flag=1} flag && /patch:/{gsub(/[^0-9]/,"",$0); print; exit}' "$lib")"

    if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
        violate spec-version-sync "$lib" \
            "could not parse PROTOCOL_VERSION fields (major/minor/patch)"
        return
    fi

    local code_version="${major}.${minor}.${patch}"

    # The changelog's version may carry a pre-release suffix (e.g.
    # `0.2.0-draft.2`); the code constant won't. Compare the
    # `MAJOR.MINOR.PATCH` head only.
    local changelog_core="${head_version%%-*}"

    if [[ "$changelog_core" != "$code_version" ]]; then
        violate spec-version-sync "$changelog" \
            "head version '$head_version' (core '$changelog_core') disagrees with PROTOCOL_VERSION '$code_version' in crates/phux-protocol/src/lib.rs"
    fi
}

# ---------------------------------------------------------------------------
# Gate 7: impl-status
# ---------------------------------------------------------------------------

# docs/spec/ and docs/consumers/ describe behavior before it exists — that is
# what spec-first means. The hazard is that a reader cannot tell which
# sentences are shipped, and the repo has been bitten: tui.md §10 specified a
# `phux capture --record` verb and a server-side output tee in the present
# tense, and neither was ever built.
#
# The contract (docs/CONVENTIONS.md §"Implementation status") is that an
# unbuilt surface carries a status claim naming a code symbol. This gate
# resolves every such claim against the code, in BOTH directions: a
# `spec-only` marker whose symbol now exists fails just as loudly as a
# `shipped` claim whose symbol does not. Stale-in-the-other-direction is the
# drift that actually recurs, because implementing something rarely prompts
# anyone to go re-read the prose that said it was unimplemented.
#
# Two carriers, one vocabulary (`shipped` / `partial` / `spec-only`, plus
# `TBD` for an unallocated reservation):
#
#   1. Catalog-table rows, whose last cell is the status word. Resolved
#      against the wire discriminant constants in phux-protocol.
#   2. Prose sections, which carry an HTML comment naming an arbitrary probe
#      symbol immediately above a reader-visible `> **Status` callout.
#
# The gate cannot catch unmarked prose about an unbuilt feature — nothing
# mechanical can. It catches the claims that are made.

IMPL_STATUS_VOCAB='^(shipped|partial|spec-only|TBD)$'

# The crate tree with comment-only lines stripped, materialized once. Every
# probe then costs one grep of one file instead of a walk of the workspace.
IMPL_CODE_CACHE=""

# Built once by gate_impl_status, never from inside a command substitution —
# a subshell would populate a copy of the variable and fire the cleanup trap
# on its own exit, deleting the file out from under the caller.
impl_code_cache_init() {
    [[ -n "$IMPL_CODE_CACHE" ]] && return 0
    IMPL_CODE_CACHE="$(mktemp "${TMPDIR:-/tmp}/phux-impl-status.XXXXXX")"
    # shellcheck disable=SC2064
    trap "rm -f '$IMPL_CODE_CACHE'" EXIT
    # The comment filter is what makes a `spec-only` claim meaningful:
    # `RolePolicy` is named in a phux-protocol doc comment that explains it is
    # unencoded, and a naive grep would read that explanation as evidence of
    # implementation.
    find "$ROOT/crates" -type f -name '*.rs' -not -path '*/target/*' \
        -print0 \
        | xargs -0 cat \
        | grep -vE '^[[:space:]]*(//|/\*|\*)' > "$IMPL_CODE_CACHE" || true
}

trim() {
    local s="$1"
    s="${s#"${s%%[![:space:]]*}"}"
    s="${s%"${s##*[![:space:]]}"}"
    printf '%s' "$s"
}

# Does `probe` appear on a non-comment line of any crate source?
#
# Word boundaries are spelled out rather than using `\b`, which is a GNU
# extension: `TYPE_SUBSCRIBE` must not match `TYPE_SUBSCRIBE_EVENTS`.
probe_matches() {
    local probe="$1"
    grep -qE "(^|[^A-Za-z0-9_])${probe}([^A-Za-z0-9_]|\$)" "$IMPL_CODE_CACHE"
}

# Is there a wire discriminant constant for this message/command name?
# The trailing colon anchors the match to the declaration, so `TYPE_SUBSCRIBE`
# is not satisfied by `TYPE_SUBSCRIBE_EVENTS`.
WIRE_CONSTS=""

wire_const_exists() {
    if [[ -z "$WIRE_CONSTS" ]]; then
        WIRE_CONSTS="$(grep -rhoE 'const (TYPE|COMMAND_TAG)_[A-Z0-9_]+:' \
            "$ROOT/crates/phux-protocol/src/wire" 2>/dev/null || true)"
    fi
    printf '%s\n' "$WIRE_CONSTS" \
        | grep -qxE "const (TYPE|COMMAND_TAG)_${1}:"
}

# Carrier 1 — catalog tables under docs/spec/.
impl_status_tables() {
    local file line row last name probe_ok fenced
    local name_re='`([A-Z][A-Z0-9_]+)`'
    for file in "${FILES[@]}"; do
        case "$file" in
            "$ROOT"/docs/spec/*) ;;
            *) continue ;;
        esac
        # The changelog narrates past releases in prose; its rows are not
        # status claims about the current tree.
        [[ "$file" == "$ROOT/docs/spec/CHANGELOG.md" ]] && continue

        fenced=0
        while IFS= read -r line; do
            # Wire-body listings inside fences are illustrations, not claims.
            if [[ "$line" == '```'* ]]; then
                fenced=$((1 - fenced))
                continue
            fi
            [[ "$fenced" -eq 1 ]] && continue
            [[ "$line" == \|* ]] || continue
            row="$(trim "$line")"
            row="${row%|}"
            last="$(trim "${row##*|}")"
            [[ "$last" =~ $IMPL_STATUS_VOCAB ]] || continue

            name=""
            if [[ "$row" =~ $name_re ]]; then
                name="${BASH_REMATCH[1]}"
            fi
            if [[ -z "$name" ]]; then
                violate impl-status "$file" \
                    "table row claims '$last' but names no \`MESSAGE_NAME\` to resolve it against: $row"
                continue
            fi

            probe_ok=0
            wire_const_exists "$name" && probe_ok=1

            case "$last" in
                shipped|partial)
                    if [[ "$probe_ok" -eq 0 ]]; then
                        violate impl-status "$file" \
                            "\`$name\` is marked '$last' but no TYPE_$name / COMMAND_TAG_$name constant exists in crates/phux-protocol/src/wire/ — mark it 'spec-only' or wire it up"
                    fi
                    ;;
                spec-only|TBD)
                    if [[ "$probe_ok" -eq 1 ]]; then
                        violate impl-status "$file" \
                            "\`$name\` is marked '$last' but crates/phux-protocol/src/wire/ declares its discriminant — the codec shipped and the doc did not follow"
                    fi
                    ;;
            esac
        done < "$file"
    done
}

# Carrier 2 — prose markers, anywhere in the doc tree, plus the reverse rule
# that a `> **Status` callout under docs/spec/ or docs/consumers/ must have a
# marker behind it. An unchecked status claim is exactly what this mechanism
# exists to retire.
impl_status_markers() {
    local file line lineno status probes probe
    local marker_re='^<!--[[:space:]]*impl-status:[[:space:]]*([A-Za-z-]+);[[:space:]]*probe:[[:space:]]*([A-Za-z0-9_,:-]+)[[:space:]]*-->[[:space:]]*$'
    local probe_re='^[A-Za-z_][A-Za-z0-9_:-]*$'
    local scoped pending_marker fenced
    for file in "${FILES[@]}"; do
        scoped=0
        case "$file" in
            "$ROOT"/docs/spec/*|"$ROOT"/docs/consumers/*) scoped=1 ;;
        esac

        lineno=0
        fenced=0
        # `pending_marker` is the status of a marker awaiting its callout;
        # empty means the previous content line was not a marker.
        pending_marker=""
        while IFS= read -r line; do
            lineno=$((lineno + 1))
            line="${line%$'\r'}"

            # A fenced block is showing the reader what a marker looks like
            # (docs/CONVENTIONS.md does exactly this), not making a claim.
            if [[ "$line" == '```'* ]]; then
                fenced=$((1 - fenced))
                continue
            fi
            [[ "$fenced" -eq 1 ]] && continue

            if [[ "$line" =~ $marker_re ]]; then
                status="${BASH_REMATCH[1]}"
                probes="${BASH_REMATCH[2]}"
                if ! [[ "$status" =~ $IMPL_STATUS_VOCAB ]]; then
                    violate impl-status "$file" \
                        "line $lineno: unknown impl-status '$status' (allowed: shipped, partial, spec-only, TBD)"
                    pending_marker="invalid"
                    continue
                fi
                local IFS_SAVE="$IFS"
                IFS=','
                # shellcheck disable=SC2086
                set -- $probes
                IFS="$IFS_SAVE"
                for probe in "$@"; do
                    if ! [[ "$probe" =~ $probe_re ]]; then
                        violate impl-status "$file" \
                            "line $lineno: probe '$probe' is not a plain symbol (letters, digits, '_', ':', '-')"
                        continue
                    fi
                    if probe_matches "$probe"; then
                        if [[ "$status" == "spec-only" || "$status" == "TBD" ]]; then
                            violate impl-status "$file" \
                                "line $lineno: marked '$status' but probe '$probe' matches non-comment code under crates/ — the implementation landed and the prose did not follow"
                        fi
                    else
                        if [[ "$status" == "shipped" || "$status" == "partial" ]]; then
                            violate impl-status "$file" \
                                "line $lineno: marked '$status' but probe '$probe' matches no non-comment code under crates/ — fix the probe or the claim"
                        fi
                    fi
                done
                pending_marker="$status"
                continue
            fi

            # Blank lines neither satisfy nor clear a pending marker.
            [[ "$line" =~ ^[[:space:]]*$ ]] && continue

            if [[ "$line" == '> **Status'* ]]; then
                if [[ -z "$pending_marker" && "$scoped" -eq 1 ]]; then
                    violate impl-status "$file" \
                        "line $lineno: '> **Status' callout with no '<!-- impl-status: ... -->' marker above it (docs/CONVENTIONS.md §Implementation status)"
                fi
            elif [[ -n "$pending_marker" ]]; then
                violate impl-status "$file" \
                    "line $lineno: impl-status marker is not followed by a '> **Status' callout; the machine-readable claim needs a reader-visible one"
            fi
            pending_marker=""
        done < "$file"

        if [[ -n "$pending_marker" ]]; then
            violate impl-status "$file" \
                "trailing impl-status marker with no '> **Status' callout after it"
        fi
    done
}

gate_impl_status() {
    impl_code_cache_init
    impl_status_tables
    impl_status_markers
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

run_gate() {
    local gate="$1"
    should_run "$gate" || return 0
    case "$gate" in
        frontmatter-present) gate_frontmatter_present ;;
        frontmatter-valid)   gate_frontmatter_valid   ;;
        tldr-present)        gate_tldr_present        ;;
        dead-link)           gate_dead_link           ;;
        adr-status)          gate_adr_status          ;;
        adr-number-unique)   gate_adr_number_unique   ;;
        adr-index-sync)      gate_adr_index_sync      ;;
        spec-version-sync)   gate_spec_version_sync   ;;
        impl-status)         gate_impl_status         ;;
        *) echo "internal error: unknown gate '$gate'" >&2; exit 2 ;;
    esac
}

for gate in "${ALL_GATES[@]}"; do
    run_gate "$gate"
done

echo "checked ${#FILES[@]} files, ${VIOLATIONS} violations"

if (( VIOLATIONS > 0 )); then
    exit 1
fi
exit 0
