import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "zod";

// The `docs` collection is sourced from `src/content/docs/_synced/`, which is
// generated by `scripts/sync-docs.ts` (gitignored, regenerated at build). The
// glob loader's `id` becomes the slug we route on (e.g. "wire/l1").
const docs = defineCollection({
  loader: glob({
    pattern: "**/*.md",
    base: "./src/content/docs/_synced",
    // Section READMEs are written as `<prefix>/index.md` (the Fumadocs folder
    // convention), but the URL slug stays the bare prefix — normalize it back
    // here so routing, the page tree, and the site routes are unchanged
    // ("quickstart/index" -> "quickstart", "wire/l1" -> "wire/l1").
    generateId: ({ entry }) => {
      const rel = entry.replace(/\.md$/, "").replace(/\\/g, "/");
      return rel.replace(/\/index$/, "");
    },
  }),
  schema: z.object({
    // Page title (derived from the source H1 by the sync script).
    title: z.string(),
    // One-line summary (derived from the source "**TL;DR.**" paragraph). Used
    // for the sidebar, breadcrumb meta, and the page <meta description>.
    summary: z.string().default(""),
    // Short scan-oriented copy for page chrome and metadata.
    description: z.string().default(""),
    codeLanguages: z.array(z.string()).default([]),
    // Sidebar group label, derived from the public information architecture.
    group: z.string(),
    // Sort order within the group.
    order: z.number().default(0),
    // Source path in the phux repo (e.g. "docs/spec/L1.md") — shown as
    // provenance / "edit on GitHub" target.
    sourcePath: z.string(),
    // Immutable provenance for the exact upstream checkout used by this build.
    sourceRevision: z.string().regex(/^[0-9a-f]{40}$/i),
    protocolVersion: z.string(),
    projectVersion: z.string(),
    // phux maturity marker carried over from source frontmatter.
    stability: z.enum(["stable", "evolving", "draft"]).default("stable"),
  }),
});

// Fumadocs folder metadata (generated by sync-docs.ts into each `_synced`
// folder as `meta.json`) — display title + explicit page order.
const meta = defineCollection({
  loader: glob({
    pattern: "**/meta.json",
    base: "./src/content/docs/_synced",
  }),
  schema: z.object({
    title: z.string().optional(),
    defaultOpen: z.boolean().optional(),
    collapsible: z.boolean().optional(),
    pages: z.array(z.string()).optional(),
  }),
});

export const collections = { docs, meta };
