#!/usr/bin/env bun
/**
 * sync-docs.ts — DRY docs pipeline for phux.sh
 * ----------------------------------------------------------------------------
 * Reads selected markdown from the phux source repo and writes it into
 * `src/content/docs/_synced/` as the source for an Astro content collection.
 *
 * We do NOT hand-copy docs. Everything under `_synced/` is gitignored and
 * regenerated by this script. If a synced page renders wrong, FIX THIS SCRIPT
 * — never edit a file under `_synced/`.
 *
 * Discovery is GLOB-DRIVEN, not a frozen manifest. We walk a fixed set of
 * discovery roots, derive (group, slug, order) from each file's path +
 * frontmatter, and exclude anything marked internal. Adding a new spec page,
 * consumer surface, architecture note, or ADR requires zero edits here — drop
 * the file in the right directory in the phux docs repo and it flows through.
 *
 * What it does, per file:
 *   1. Strips phux's internal frontmatter (audience / stability / last-reviewed)
 *      and replaces it with the site's own collection schema frontmatter
 *      (title, summary, group, order, sourcePath, stability).
 *   1b. Section READMEs with children are written as `<prefix>/index.md`, and
 *      each section folder gets a Fumadocs `meta.json` (title + explicit
 *      `pages` order). The URL slug stays the bare prefix either way.
 *   2. Derives `title` from the first `# H1` and `summary` from the leading
 *      `**TL;DR.** …` paragraph when present.
 *   3. Rewrites relative `*.md` links between docs into site routes
 *      (e.g. `../spec/L1.md` -> `/wire/l1`, `./0030-...md` -> `/decisions/adr-0030`).
 *   4. Rewrites links to files that DON'T live on this site (crates/, research/,
 *      CONTRIBUTING.md, README.md) into absolute GitHub URLs so they still work.
 *   5. Skips internal docs (`stability: scratch` or `draft`, plus a small
 *      path denylist).
 *
 * Idempotent: the `_synced/` dir is wiped and rebuilt on every run, so a clean
 * `bun run sync-docs` always produces the same tree from the same source.
 *
 * Env:
 *   PHUX_DOCS_DIR  — phux `docs/` dir. Default: `..` — the site lives at
 *                    `docs/site/` inside the phux repo, so the docs tree is
 *                    one level up. Override only for exotic checkouts.
 *
 * CI / rebuild trigger:
 *
 *   Site and docs share one repository, so `.github/workflows/deploy-site.yml`
 *   at the repo root rebuilds and deploys on every push that touches `docs/**`
 *   or `ADR/**`. No cross-repo dispatch, no scheduled drift polling.
 *
 *   For local dev, PHUX_DOCS_DIR defaults to `../` and Just Works.
 * ---------------------------------------------------------------------------
 */

import { execFileSync } from "node:child_process";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const DOCS_DIR = resolve(ROOT, process.env.PHUX_DOCS_DIR ?? "..");
// ADR lives a level up from docs/ in the phux repo.
const ADR_DIR = resolve(DOCS_DIR, "../ADR");
const PHUX_ROOT = resolve(DOCS_DIR, "..");
const OUT_DIR = join(ROOT, "src/content/docs/_synced");
const MANIFEST_PATH = join(ROOT, "public/docs-manifest.json");

// The curl installers are published from this same repo, the same way the docs
// are: each `scripts/install*.sh` is the only copy, and the site serves its
// bytes verbatim. Both filenames get the identical script rather than one
// redirecting to the other, so `curl https://phux.sh/install` needs no -L to
// follow.
const INSTALLERS: { src: string; dests: readonly [string, string] }[] = [
  {
    src: join(PHUX_ROOT, "scripts/install.sh"),
    dests: ["public/install", "public/install.sh"],
  },
  {
    src: join(PHUX_ROOT, "scripts/install-cockpit.sh"),
    dests: ["public/install-cockpit", "public/install-cockpit.sh"],
  },
];

function sourceRevision(): string {
  const revision =
    process.env.PHUX_SOURCE_REVISION ??
    execFileSync("git", ["-C", PHUX_ROOT, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  if (!/^[0-9a-f]{40}$/i.test(revision)) throw new Error(`invalid phux source revision: ${revision}`);
  return revision;
}

const SOURCE_REVISION = sourceRevision();
const GH_BLOB = `https://github.com/no-phux/phux/blob/${SOURCE_REVISION}`;
const GH_TREE = `https://github.com/no-phux/phux/tree/${SOURCE_REVISION}`;

/**
 * Publish the installer scripts at /install(+.sh) and /install-cockpit(+.sh).
 *
 * Nothing here is committed — every destination is gitignored and rewritten on
 * every build — so the bytes a stranger pipes to `sh` cannot drift from the
 * scripts `scripts/test-install.sh` exercises. The shebang assertion is the
 * cheap half of that contract: a served script is consumed by `sh`, and a
 * bash shebang means somebody reintroduced bashisms that dash will reject on a
 * user's machine rather than in CI.
 */
async function syncInstaller(): Promise<void> {
  for (const { src, dests } of INSTALLERS) {
    const script = await readFile(src, "utf8");
    if (!script.startsWith("#!/bin/sh\n")) {
      throw new Error(
        `${src} must start with #!/bin/sh: it is served at https://phux.sh and piped straight to sh`,
      );
    }
    for (const dest of dests) {
      await writeFile(join(ROOT, dest), script, { mode: 0o755 });
    }
  }
  console.log("sync-docs: published the installers at /install and /install-cockpit (+.sh)");
}

/** Nav groups, in sidebar render order. */
const GROUPS = {
  start: "Get started",
  use: "Use & automate",
  protocol: "Protocol reference",
  internals: "Architecture & operations",
  records: "Project record",
} as const;
type Group = keyof typeof GROUPS;

interface Entry {
  /** Source path relative to the phux REPO root, e.g. "docs/spec/L1.md". */
  repoPath: string;
  /** Absolute path on disk to read from. */
  abs: string;
  /** Site collection slug (also the URL tail). */
  slug: string;
  group: Group;
  order: number;
  /** Title override; otherwise derived from the H1. */
  title?: string;
  /** Optional exact H2 section numbers to publish from a monolithic source. */
  sections?: number[];
  /** Metadata summary override for virtual task-sized pages. */
  summary?: string;
}

// ── frontmatter ──────────────────────────────────────────────────────────
interface SourceFm {
  body: string;
  meta: Record<string, string>;
}

function parseFrontmatter(raw: string): SourceFm {
  if (!raw.startsWith("---\n")) return { body: raw, meta: {} };
  const end = raw.indexOf("\n---", 4);
  if (end === -1) return { body: raw, meta: {} };
  const block = raw.slice(4, end);
  const body = raw.slice(end + 4).replace(/^\n/, "");
  const meta: Record<string, string> = {};
  for (const line of block.split("\n")) {
    const m = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (m) meta[m[1]] = m[2].trim();
  }
  return { body, meta };
}

// ── discovery ──────────────────────────────────────────────────────────────
/**
 * Orientation singles: standalone top-level docs that don't belong to a
 * section tree. Each keeps an explicit (slug, group, order). Path is relative
 * to DOCS_DIR.
 */
const ORIENTATION: { file: string; slug: string; group: Group; order: number }[] = [
  { file: "README.md", slug: "docs", group: "start", order: 0 },
  { file: "QUICKSTART.md", slug: "quickstart", group: "start", order: 1 },
  { file: "INSTALL.md", slug: "quickstart/install", group: "start", order: 2 },
  { file: "CONCEPTS.md", slug: "concepts", group: "start", order: 3 },
  { file: "when-to-use.md", slug: "concepts/when-to-use", group: "start", order: 4 },
  { file: "CONFIG.md", slug: "quickstart/config", group: "use", order: 0 },
  { file: "remote-access.md", slug: "remote-access", group: "use", order: 4 },
  { file: "operations.md", slug: "architecture/operations", group: "internals", order: 0 },
  { file: "vision.md", slug: "concepts/vision", group: "records", order: 0 },
];

/**
 * Section roots: directory trees walked recursively. Each maps a directory
 * (relative to DOCS_DIR) onto a nav group and a URL prefix. The directory's
 * README becomes the section index (bare slug, order 0); other files sort
 * alphabetically by basename after it.
 */
const SECTION_ROOTS: { dir: string; group: Group; urlPrefix: string }[] = [
  { dir: "consumers", group: "use", urlPrefix: "consumers" },
  { dir: "reference", group: "use", urlPrefix: "reference" },
  { dir: "spec", group: "protocol", urlPrefix: "wire" },
  { dir: "architecture", group: "internals", urlPrefix: "architecture" },
];

/**
 * Path denylist — internal docs that aren't marked `scratch` but still must
 * never publish. Keyed on repo-relative path.
 */
const DENYLIST = new Set<string>([
  "docs/demo.md",
  "docs/CONVENTIONS.md",
  "docs/architecture/DIAGRAM.md",
  "docs/architecture/l2-server-design.md",
]);

/** Stability values that mark a doc as internal / unpublishable. */
const EXCLUDED_STABILITY = new Set(["scratch", "draft"]);

/** Recursively list all `*.md` files under `dir` (absolute paths). */
async function walkMd(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const ent of entries) {
    const abs = join(dir, ent.name);
    if (ent.isDirectory()) out.push(...(await walkMd(abs)));
    else if (ent.isFile() && ent.name.endsWith(".md")) out.push(abs);
  }
  return out;
}

/** repoPath for a docs/ file given its absolute path. */
function docsRepoPath(abs: string): string {
  return `docs/${relative(DOCS_DIR, abs).split(/[\\/]/).join("/")}`;
}

/**
 * Whether a candidate file should be excluded, based on its frontmatter +
 * the path denylist. Returns the reason string, or null to keep.
 */
function exclusionReason(repoPath: string, meta: Record<string, string>): string | null {
  if (DENYLIST.has(repoPath)) return "denylist";
  if (EXCLUDED_STABILITY.has((meta.stability ?? "").toLowerCase())) {
    return `stability:${meta.stability}`;
  }
  return null;
}

/** Numeric nav-order from frontmatter, or null when absent/non-numeric. */
function navOrder(meta: Record<string, string>): number | null {
  const raw = meta["nav-order"] ?? meta["nav_order"] ?? meta["navOrder"];
  if (raw === undefined) return null;
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
}

/**
 * Walk the discovery roots and build the full set of entries. Reads each
 * candidate's frontmatter to apply the exclusion rules and read nav-order.
 */
async function discover(): Promise<{ entries: Entry[]; excluded: string[] }> {
  const entries: Entry[] = [];
  const excluded: string[] = [];

  // 1) Orientation singles (explicit map).
  for (const o of ORIENTATION) {
    const abs = join(DOCS_DIR, o.file);
    const repoPath = `docs/${o.file}`;
    let raw: string;
    try {
      raw = await readFile(abs, "utf8");
    } catch {
      console.warn(`  skip (missing): ${repoPath}`);
      continue;
    }
    const { meta } = parseFrontmatter(raw);
    const reason = exclusionReason(repoPath, meta);
    if (reason) {
      excluded.push(`${repoPath} (${reason})`);
      continue;
    }
    entries.push({ repoPath, abs, slug: o.slug, group: o.group, order: o.order });
  }

  // 2) Section roots (globbed, alpha-ordered with README first).
  for (const root of SECTION_ROOTS) {
    const rootDir = join(DOCS_DIR, root.dir);
    const files = (await walkMd(rootDir)).sort((a, b) => a.localeCompare(b));

    // Read + filter first so ordering is computed over the kept set only.
    const kept: { abs: string; repoPath: string; meta: Record<string, string> }[] = [];
    for (const abs of files) {
      const repoPath = docsRepoPath(abs);
      const raw = await readFile(abs, "utf8");
      const { meta } = parseFrontmatter(raw);
      const reason = exclusionReason(repoPath, meta);
      if (reason) {
        excluded.push(`${repoPath} (${reason})`);
        continue;
      }
      kept.push({ abs, repoPath, meta });
    }

    // Non-README files: explicit nav-order wins, else alpha (stable index).
    const nonReadme = kept.filter((k) => basename(k.abs).toLowerCase() !== "readme.md");
    nonReadme.sort((a, b) => {
      const na = navOrder(a.meta);
      const nb = navOrder(b.meta);
      if (na !== null && nb !== null && na !== nb) return na - nb;
      if (na !== null && nb === null) return -1;
      if (na === null && nb !== null) return 1;
      return basename(a.abs).localeCompare(basename(b.abs));
    });

    for (const k of kept) {
      const file = basename(k.abs);
      const isReadme = file.toLowerCase() === "readme.md";
      const relInRoot = relative(rootDir, k.abs).split(/[\\/]/).join("/");
      let slug: string;
      let order: number;
      if (isReadme) {
        // Section README -> bare section slug (the index), order 0.
        // Nested READMEs (rare) keep their dir as the slug tail.
        const dir = dirname(relInRoot);
        slug = dir === "." ? root.urlPrefix : `${root.urlPrefix}/${dir}`;
        order = 0;
      } else {
        // strip the .md extension; keep nested path under the section.
        // Lowercase the tail so source casing (L1.md, CHANGELOG.md) maps onto
        // stable lowercase URLs (/wire/l1, /wire/changelog).
        const noExt = relInRoot.replace(/\.md$/, "").toLowerCase();
        slug = `${root.urlPrefix}/${noExt}`;
        order = nonReadme.indexOf(k) + 1; // after the README index
      }
      entries.push({ repoPath: k.repoPath, abs: k.abs, slug, group: root.group, order });
    }
  }

  // 3) ADRs -> Project record. README is the index (slug "decisions", order 0);
  // each NNNN-*.md becomes decisions/adr-NNNN ordered by its number.
  const adrFiles = (await walkMd(ADR_DIR)).sort((a, b) => a.localeCompare(b));
  for (const abs of adrFiles) {
    const file = basename(abs);
    const repoPath = `ADR/${relative(ADR_DIR, abs).split(/[\\/]/).join("/")}`;
    const raw = await readFile(abs, "utf8");
    const { meta } = parseFrontmatter(raw);
    if (EXCLUDED_STABILITY.has((meta.stability ?? "").toLowerCase())) {
      excluded.push(`${repoPath} (stability:${meta.stability})`);
      continue;
    }
    if (file.toLowerCase() === "readme.md") {
      entries.push({
        repoPath,
        abs,
        slug: "decisions",
        group: "records",
        order: 0,
        title: "Decision Records",
      });
      continue;
    }
    const m = file.match(/^(\d{4})-/);
    if (!m) {
      excluded.push(`${repoPath} (no NNNN- prefix)`);
      continue;
    }
    const num = m[1];
    entries.push({
      repoPath,
      abs,
      slug: `decisions/adr-${num}`,
      group: "records",
      // Index is 0; ADRs sort after it by number. +1 keeps README first.
      order: Number(num),
    });
  }

  splitLongGuide(entries, "docs/consumers/agents.md", [
    {
      slug: "consumers/agents",
      title: "Agents and automation",
      sections: [0, 1, 5],
      summary: "Use the read-act-wait loop to inspect and drive shared terminals, then go deeper only when you need exact CLI or JSON contracts.",
    },
    { slug: "consumers/agents/cli", title: "Agent CLI", sections: [2] },
    { slug: "consumers/agents/targeting", title: "Agent targeting", sections: [3] },
    { slug: "consumers/agents/json", title: "Agent JSON contracts", sections: [4] },
    { slug: "consumers/agents/integrations", title: "Agent integrations", sections: [6] },
  ]);
  splitLongGuide(entries, "docs/consumers/tui.md", [
    {
      slug: "consumers/tui",
      title: "Interactive TUI",
      sections: [0, 2, 13],
      summary: "Use phux interactively: understand the terminal model, navigate the first session, then open focused guides for commands and customization.",
    },
    { slug: "consumers/tui/commands", title: "TUI commands and selectors", sections: [1, 3] },
    { slug: "consumers/tui/configuration", title: "TUI configuration and keybindings", sections: [4, 5] },
    { slug: "consumers/tui/interface", title: "TUI layout, mouse, and status bar", sections: [6, 7, 8] },
    { slug: "consumers/tui/automation", title: "TUI hooks and recording", sections: [9, 10] },
    { slug: "consumers/tui/reference", title: "TUI defaults and scope", sections: [11, 12, 14] },
  ]);

  return { entries, excluded };
}

function splitLongGuide(
  entries: Entry[],
  repoPath: string,
  pages: { slug: string; title: string; sections: number[]; summary?: string }[],
) {
  const index = entries.findIndex((entry) => entry.repoPath === repoPath);
  if (index === -1) return;
  const source = entries[index];
  entries.splice(
    index,
    1,
    ...pages.map((page, order) => ({ ...source, ...page, order: source.order + order / 10 })),
  );
}

// ── routing tables (derived from DISCOVERED entries) ─────────────────────────
function siteRoute(slug: string): string {
  return slug === "" ? "/" : `/${slug}`;
}

function normalizeRepoPath(p: string): string {
  // Collapse ./ and ../ segments; strip leading ./
  const parts: string[] = [];
  for (const seg of p.split("/")) {
    if (seg === "" || seg === ".") continue;
    if (seg === "..") parts.pop();
    else parts.push(seg);
  }
  return parts.join("/");
}

let ROUTE_BY_REPO_PATH = new Map<string, string>();
let ROUTE_BY_DIR = new Map<string, string>();

function buildRouteTables(entries: Entry[]) {
  ROUTE_BY_REPO_PATH = new Map();
  for (const e of entries) {
    const repoPath = normalizeRepoPath(e.repoPath);
    if (!ROUTE_BY_REPO_PATH.has(repoPath)) ROUTE_BY_REPO_PATH.set(repoPath, siteRoute(e.slug));
  }
  // Directory targets — links like `../../ADR/` or `./spec/` resolve to the
  // matching index route on the site rather than a raw GitHub tree. Derived
  // from each section's index slug.
  ROUTE_BY_DIR = new Map<string, string>([
    ["ADR", "/decisions"],
    ["docs/spec", "/wire"],
    ["docs/consumers", "/consumers"],
    ["docs/reference", "/reference"],
    ["docs/architecture", "/architecture"],
  ]);
}

function deriveTitle(body: string): string | null {
  const m = body.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : null;
}

function deriveSummary(body: string): string | null {
  // Leading "**TL;DR.** …" paragraph — strip markdown emphasis + inline code,
  // collapse whitespace, cap length for the sidebar / meta description.
  const m = body.match(/\*\*TL;DR\.?\*\*\s*([\s\S]*?)(?:\n\n|\n#)/);
  if (!m) return null;
  let s = m[1]
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
  return s || null;
}

function deriveDescription(summary: string): string {
  if (summary.length <= 160) return summary;
  const sentence = summary.slice(0, 160).match(/^(.{60,}?[.!?])(?:\s|$)/)?.[1];
  return sentence ?? `${summary.slice(0, 157).replace(/\s+\S*$/, "")}...`;
}

function codeLanguages(body: string): string[] {
  const languages: string[] = [];
  let open = false;
  for (const line of body.split("\n")) {
    const fence = line.match(/^```([^`]*)$/);
    if (!fence) continue;
    if (!open) languages.push(fence[1].trim().split(/\s+/)[0] || "text");
    open = !open;
  }
  return languages;
}

/** The docs shell owns the page title and lede; avoid rendering source copies. */
function stripSourceLead(body: string): string {
  return body
    .replace(/^\s+/, "")
    .replace(/^#\s+.+\n+/, "")
    .replace(/^\*\*TL;DR\.?\*\*[\s\S]*?\n\s*\n/, "")
    .replace(/^\s*---\s*\n+/, "")
    .replace(/^\s+/, "");
}

/** Render the changelog as addressable entries instead of paragraph-sized table cells. */
function presentBody(body: string, slug: string, sections?: number[]): string {
  const stripped = stripSourceLead(body);
  if (sections) return selectNumberedSections(stripped, sections);
  if (slug !== "wire/changelog") return stripped;

  const lines = stripped.split("\n");
  const tableStart = lines.findIndex((line) => /^\|\s*Version\s*\|/i.test(line));
  if (tableStart === -1) return stripped;
  let tableEnd = tableStart + 2;
  while (tableEnd < lines.length && lines[tableEnd].startsWith("|")) tableEnd++;

  const entries = lines.slice(tableStart + 2, tableEnd).flatMap((line) => {
    // Only the first two pipes are structural. Notes contain escaped wire
    // notation such as `a \|\| b`, which must remain intact.
    const row = line.match(/^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*(.*)\s*\|\s*$/);
    if (!row) return [];
    const [, version, date, notes] = row;
    return [`## ${version}`, "", `**${date}**`, "", notes, ""];
  });
  return [...lines.slice(0, tableStart), ...entries, ...lines.slice(tableEnd)].join("\n");
}

function selectNumberedSections(body: string, selected: number[]): string {
  const matches = [...body.matchAll(/^##\s+(\d+)\.\s+.+$/gm)];
  const sections: string[] = [];
  for (let i = 0; i < matches.length; i++) {
    const number = Number(matches[i][1]);
    if (!selected.includes(number)) continue;
    const start = matches[i].index!;
    const end = matches[i + 1]?.index ?? body.length;
    sections.push(body.slice(start, end).trim());
  }
  if (sections.length !== selected.length) {
    throw new Error(`could not extract sections ${selected.join(", ")}`);
  }
  return `${sections.join("\n\n")}\n`;
}

// ── link rewriting ─────────────────────────────────────────────────────────
/**
 * Rewrite every relative markdown link in `body`. `repoPath` is the source
 * file's path from the phux repo root (e.g. "docs/spec/L1.md"), used to
 * resolve relative hrefs.
 */
function rewriteLinks(body: string, repoPath: string): string {
  const fromDir = dirname(repoPath); // e.g. "docs/spec"

  // Inline links: [text](href). Leave images/code-fences alone via a simple
  // href filter (we only touch intra-repo relative paths).
  let out = body.replace(/(\]\()([^)\s]+)(\))/g, (whole, open, href, close) => {
    const next = resolveHref(href, fromDir);
    return next === null ? whole : `${open}${next}${close}`;
  });

  // Reference-style link definitions: `[label]: href "optional title"`. These
  // sit at the start of a line and are invisible to the inline-link pass above —
  // phux's spec uses them heavily for ADR references, so they must be rewritten
  // too or they 404 on the site.
  out = out.replace(
    /^([ \t]*\[[^\]]+\]:[ \t]*)(\S+)([ \t]*(?:"[^"]*"|'[^']*'|\([^)]*\))?[ \t]*)$/gm,
    (whole, prefix, href, suffix) => {
      const next = resolveHref(href, fromDir);
      return next === null ? whole : `${prefix}${next}${suffix}`;
    },
  );

  return out;
}

/**
 * Resolve a single relative href to its site route / GitHub URL, or return
 * null to leave it untouched (external, anchor-only, mailto, unrecognized).
 * Shared by the inline-link and reference-definition passes.
 */
function resolveHref(href: string, fromDir: string): string | null {
  if (/^https?:\/\//.test(href) || href.startsWith("#") || href.startsWith("mailto:")) {
    return null;
  }
  const hashIdx = href.indexOf("#");
  const path = hashIdx === -1 ? href : href.slice(0, hashIdx);
  const anchor = hashIdx === -1 ? "" : href.slice(hashIdx);
  if (!path) return null; // pure anchor

  const resolved = normalizeRepoPath(join(fromDir, path));

  // 1) Links to a doc we render -> site route.
  const route = ROUTE_BY_REPO_PATH.get(resolved);
  if (route) return `${route}${anchor}`;

  // 2) Directory link to a section we host -> that section's index route.
  const isDir = path.endsWith("/") || !/\.[a-z0-9]+$/i.test(path);
  if (isDir) {
    const dirRoute = ROUTE_BY_DIR.get(resolved);
    if (dirRoute) return `${dirRoute}${anchor}`;
    return `${GH_TREE}/${resolved}${anchor}`;
  }

  // 3) Markdown / source links to repo files we DON'T host -> GitHub blob URL.
  if (path.endsWith(".md") || /\.(rs|toml|zig|sh|nix|ya?ml)$/.test(path) || resolved.includes("/")) {
    return `${GH_BLOB}/${resolved}${anchor}`;
  }
  return null;
}

// ── yaml-safe scalar ────────────────────────────────────────────────────────
function yamlString(s: string): string {
  // Always quote; escape backslashes and double-quotes for YAML double-quoted.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// The site's collection schema only knows these maturity markers; map any
// other source value (e.g. "evolving" is allowed; "scratch" is filtered out
// upstream) defensively onto a safe default.
const SCHEMA_STABILITY = new Set(["stable", "evolving", "draft"]);

/**
 * Fumadocs sidebar folder labels, by section prefix. Everything is lowercase /
 * terminal-native to match the site's voice (the old flat groups are gone).
 */
const FOLDER_TITLES: Record<string, string> = {
  quickstart: "quickstart",
  concepts: "concepts",
  consumers: "guides",
  "consumers/agents": "agents and automation",
  "consumers/tui": "interactive TUI",
  reference: "reference",
  wire: "protocol",
  architecture: "architecture",
  decisions: "decisions",
};

const ROOT_PAGES = [
  "docs",
  "quickstart",
  "concepts",
  "consumers",
  "remote-access",
  "reference",
  "wire",
  "architecture",
  "decisions",
];

const PROTOCOL_PAGES = [
  "index",
  "tutorial",
  "proto",
  "appendix-encoding",
  "l1",
  "input",
  "l3",
  "l2",
  "appendix-reserved",
  "changelog",
];

const REFERENCE_PAGES = [
  "index",
  "cli",
  "config",
  "actions",
  "widgets",
  "hooks",
  "exit-codes",
  "files",
  "deprecations",
];

const GUIDE_PAGES = [
  "index",
  "tui",
  "agents",
  "opencode",
  "pi",
  "mcp",
  "recording",
  "web",
  "ios",
  "sdk",
];

async function readVersionMetadata() {
  const [protocolSource, cargoSource] = await Promise.all([
    readFile(join(PHUX_ROOT, "crates/phux-protocol/src/lib.rs"), "utf8"),
    readFile(join(PHUX_ROOT, "Cargo.toml"), "utf8"),
  ]);
  const version = protocolSource.match(
    /PROTOCOL_VERSION:\s*Version\s*=\s*Version\s*{[\s\S]*?major:\s*(\d+)[\s\S]*?minor:\s*(\d+)[\s\S]*?patch:\s*(\d+)/,
  );
  const projectVersion = cargoSource.match(/\[workspace\.package\][\s\S]*?\nversion\s*=\s*"([^"]+)"/)?.[1];
  if (!version || !projectVersion) throw new Error("could not derive phux protocol/project version");
  return {
    protocolVersion: `${version[1]}.${version[2]}.${version[3]}`,
    projectVersion,
  };
}

// ── main ─────────────────────────────────────────────────────────────────
async function run() {
  // Fully regenerate for reproducibility / idempotency.
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const versions = await readVersionMetadata();
  let { entries, excluded } = await discover();

  // Orientation singles and section roots can both map the same file (e.g.
  // `operations.md` is oriented AND walked under `architecture/`). Keep one
  // entry per slug, first occurrence wins — same file content either way.
  const seen = new Map<string, string>();
  entries = entries.filter((e) => {
    const previous = seen.get(e.slug);
    if (previous && previous !== e.repoPath) {
      throw new Error(`duplicate slug ${e.slug}: ${previous} and ${e.repoPath}`);
    }
    if (previous) return false;
    seen.set(e.slug, e.repoPath);
    return true;
  });
  buildRouteTables(entries);

  // A section README that has children becomes `<prefix>/index.md` (the
  // Fumadocs folder convention) so the page tree has one "quickstart" entry,
  // not a page + a duplicate folder.
  const folderPrefixes = new Set<string>();
  for (const e of entries) {
    const i = e.slug.lastIndexOf("/");
    if (i > 0) folderPrefixes.add(e.slug.slice(0, i));
  }

  let written = 0;
  const failed: string[] = [];

  for (const e of entries) {
    let raw: string;
    try {
      raw = await readFile(e.abs, "utf8");
    } catch {
      console.warn(`  fail (read):    ${e.repoPath}`);
      failed.push(e.repoPath);
      continue;
    }

    const { body, meta } = parseFrontmatter(raw);
    const title = e.title ?? deriveTitle(body) ?? e.slug;
    const summary = e.summary ?? deriveSummary(body) ?? "";
    const description = deriveDescription(summary);
    const rewritten = rewriteLinks(presentBody(body, e.slug, e.sections), e.repoPath);
    const languages = codeLanguages(rewritten);
    const stability = SCHEMA_STABILITY.has((meta.stability ?? "").toLowerCase())
      ? meta.stability
      : "stable";

    const fm = [
      "---",
      `title: ${yamlString(title)}`,
      `summary: ${yamlString(summary)}`,
      `description: ${yamlString(description)}`,
      `codeLanguages: ${JSON.stringify(languages)}`,
      `group: ${yamlString(GROUPS[e.group])}`,
      `order: ${e.order}`,
      `sourcePath: ${yamlString(e.repoPath)}`,
      `sourceRevision: ${yamlString(SOURCE_REVISION)}`,
      `protocolVersion: ${yamlString(versions.protocolVersion)}`,
      `projectVersion: ${yamlString(versions.projectVersion)}`,
      `stability: ${yamlString(stability)}`,
      "---",
      "",
    ].join("\n");

    const isIndex = folderPrefixes.has(e.slug);
    const outDir = isIndex ? join(OUT_DIR, e.slug) : OUT_DIR;
    const outFile = join(outDir, isIndex ? "index.md" : `${e.slug}.md`);
    await mkdir(dirname(outFile), { recursive: true });
    await writeFile(outFile, fm + rewritten, "utf8");
    written++;
  }

  // Fumadocs `meta.json` per folder: display title + explicit page order
  // (index first, then the sync script's discovery/nav-order). Never hand-edit.
  for (const prefix of [...folderPrefixes].sort()) {
    const folderEntries = entries.filter((e) => {
      if (e.slug === prefix) return true;
      if (!e.slug.startsWith(`${prefix}/`)) return false;
      return !e.slug.slice(prefix.length + 1).includes("/");
    });
    folderEntries.sort((a, b) => {
      if (a.slug === prefix) return -1;
      if (b.slug === prefix) return 1;
      return 0;
    });
    let pages = folderEntries.map((e) =>
      e.slug === prefix ? "index" : e.slug.slice(prefix.length + 1),
    );
    if (prefix === "wire") {
      const available = new Set(pages);
      pages = [
        ...PROTOCOL_PAGES.filter((page) => available.delete(page)),
        ...pages.filter((page) => available.has(page)),
      ];
    }
    if (prefix === "reference") {
      const available = new Set(pages);
      pages = [
        ...REFERENCE_PAGES.filter((page) => available.delete(page)),
        ...pages.filter((page) => available.has(page)),
      ];
    }
    if (prefix === "consumers") {
      const available = new Set(pages);
      pages = [
        ...GUIDE_PAGES.filter((page) => available.delete(page)),
        ...pages.filter((page) => available.has(page)),
      ];
    }
    // ADR routes remain directly addressable and searchable without dumping
    // the entire historical ledger into the default navigation tree.
    if (prefix === "decisions") pages = ["index"];
    const meta = {
      title: FOLDER_TITLES[prefix] ?? prefix,
      pages,
    };
    await writeFile(join(OUT_DIR, prefix, "meta.json"), `${JSON.stringify(meta, null, 2)}\n`);
  }

  await writeFile(
    join(OUT_DIR, "meta.json"),
    `${JSON.stringify({ pages: ROOT_PAGES }, null, 2)}\n`,
  );
  await syncInstaller();

  await writeFile(
    MANIFEST_PATH,
    `${JSON.stringify(
      {
        repository: "no-phux/phux",
        revision: SOURCE_REVISION,
        protocolVersion: versions.protocolVersion,
        projectVersion: versions.projectVersion,
      },
      null,
      2,
    )}\n`,
  );

  if (excluded.length) {
    console.log(`sync-docs: excluded ${excluded.length} internal doc(s):`);
    for (const x of excluded.sort()) console.log(`  - ${x}`);
  }
  console.log(`sync-docs: wrote ${written} page(s), from ${DOCS_DIR}`);
  if (failed.length) {
    console.error(`sync-docs: ${failed.length} file(s) failed to resolve:`);
    for (const f of failed) console.error(`  - ${f}`);
    process.exitCode = 1;
  }
  if (written === 0) {
    console.error("sync-docs: nothing written — is PHUX_DOCS_DIR correct?");
    process.exit(1);
  }
}

run().catch((err) => {
  console.error("sync-docs failed:", err);
  process.exit(1);
});
